### ISSUE TITLE
Bug: Unresponsive deployment to master branch from source branch in organisation repo

### ISSUE THREAD

**Issue by GlenTiki** [peaceiris/actions-gh-pages#100]
**Describe the bug**
When deploying my application with an organisation's github pages site, the deploy step hangs and never completes. I am running the workflow on the source branch, and pushing to the master branch, as needed.

I've ensured that the secret is configured as required, and the push key works.

**To Reproduce**
- none

**Expected behaviour**
Deployment pushes built code in ./build to master branch

**Screenshots**
<img width="1328" alt="Screenshot 2020-02-12 at 16 50 49" src="https://user-images.githubusercontent.com/6907399/74357526-f4d25380-4db7-11ea-866c-c42461ebf0b5.png">

**Your YAML file**
- https://github.com/WaterfordTech/WaterfordTech.github.io
- https://github.com/WaterfordTech/WaterfordTech.github.io/blob/source/.github/workflows/release.yml

**Comment by peaceiris** [comment]
Why did you set a passphrase? Do not set a passphrase.

**Comment by GlenTiki** [comment]
That is it - I'm sorry, no issue here. The GitHub actions UI won't show me logs for the deploy step, as you can see in my screenshot.
