### ISSUE TITLE
inconsistent handling of symbolic links in publish_dir

### ISSUE THREAD

**Issue by dhimmel** [peaceiris/actions-gh-pages#103]
I got the [following error](https://github.com/dhimmel/rootstock-actions-deploy/runs/450698715?check_suite_focus=true#step:8:41) when building https://github.com/dhimmel/rootstock-actions-deploy/commit/c29e40a702e4a7e37107e5f9b13a62a0343e816f:

```
##[error]Action failed with "Error: Error: no such file or directory: /home/runner/work/rootstock-actions-deploy/rootstock-actions-deploy/webpage/images"
##[error]Node run failed with exit code 1
```

The corresponding action step is:

```yaml
      - name: Deploy Webpage
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webpage
          publish_branch: gh-pages
```

I believe this error occurs because `webpage/images` is a symlink to another directory. The contents of the `webpage` directory, set as `publish_dir`, are something like:

> ![image](https://user-images.githubusercontent.com/1117703/74662724-733c4600-5168-11ea-9778-540d6204f00f.png)

There are several types of possible symlinks:

1. symlink to directory within publish_dir
2. symlink to a file within publish_dir
3. symlink to a directory or file outside of publish_dir

Currently, I'm interested in a solution that solves 1 & 2.

The python [ghp-import](https://github.com/davisp/ghp-import) utility has a `--follow-links` argument (see https://github.com/davisp/ghp-import/issues/37). When specified, it copies (dereferences) the contents of a symlink rather than preserving it. However, I think the ideal behavior is to preserve symlinks in categories 1 & 2 above (see https://github.com/davisp/ghp-import/issues/70), since GitHub Pages can navigate symlinks.

**Comment by dhimmel** [comment]
Before looking into this, let me confirm that it's not a bug on my end where the symlink target does not exist.

**Comment by dhimmel** [comment]
Update: the issue was on my end. Previously, I hadn't actually created the target files where the symlinks pointed. I fixed this in https://github.com/dhimmel/rootstock-actions-deploy/commit/78350c1dfd013318626fc3d12f1f2c3b9d5dd20d and [the build](https://github.com/dhimmel/rootstock-actions-deploy/runs/450813963#step:9:56) passed and properly deployed to the `gh-pages` [branch](https://github.com/dhimmel/rootstock-actions-deploy/tree/f0780948d8c68c975cab3ff1d90302e03ee0b22c).

It looks like symlinks were handled in the following way. Symlinks to files (possibility 2 above) were preserved as symlinks. Symlinks to directories (possibility 1 above) were dereferenced and their contents copied. Was this discrepancy in behavior intentional?

So @peaceiris feel free to close or rename this issue. While my original issue was my fault, there are some possible enhancements:

1. improved error message indicating that symlink target does not exist. Although frankly the error message is actually pretty good, so perhaps nothing needs to be done here.
2. consistent treatment of symlinks to files and directories
3. consideration of possibility 3 above, although this does not matter for my application.

**Comment by peaceiris** [comment]
I got it. Yes, this problem is caused by the behavior of this action.

This action copies the publish_dir to the `${HOME}/actions_github_pages/publish_dir`, so symbolic links will become unresolved links.

The copy operation depends on the [io.cp actions/toolkit](https://github.com/actions/toolkit/blob/f383109dc391f2c2576583f9426be193eeeefbfd/packages/io/src/io.ts#L34).

To solve this issue, we can:

1. Fix the `io.cp` on the upstream
2. Switch to the `rsync --copy-links`-like operation

**Comment by dhimmel** [comment]
> Yes, this problem is caused by the behavior of this action.

@peaceiris I am not sure we're on the same page. Note that the initial problem I commented on was my fault... the target of the symlink did not exist because I did not create it.

> This action copies the publish_dir to the `${HOME}/actions_github_pages/publish_dir`, so symbolic links will become unresolved links.

If the symbolic link points to a target also in `publish_dir`, the symbolic link can be preserved without  becoming unresolvable. Currently, symbolic links to files are preserved while symbolic links to directories are dereferenced.

For symbolic links that point to a target outside of `publish_dir`, then dereferencing (copying) would be required to get them to resolve once deployed to a branch.

I think the ideal behavior is to preserve symlinks whose targets are within publish_dir, while dereferencing symlinks whose targets are outside of publish_dir. However, I'm not sure how challenging that is to implement. Perhaps there could also be an option. Dereferencing all symlinks is also a solution (as in `rsync --copy-links` or `cp --recursive --dereference`).

**Comment by peaceiris** [comment]
@dhimmel
I opened #144 and released `3.6.0-0`. Could you test it?

**Comment by dhimmel** [comment]
> I think the ideal behavior is to preserve symlinks whose targets are within publish_dir, while dereferencing symlinks whose targets are outside of publish_dir.

Looks like `rsync` has an [option](https://linux.die.net/man/1/rsync) for this:

> **--copy-unsafe-links**
This tells rsync to copy the referent of symbolic links that point outside the copied tree. Absolute symlinks are also treated like ordinary files, and so are any symlinks in the source path itself when **--relative** is used. This option has no additional effect if **--copy-links** was also specified.

**Comment by peaceiris** [comment]
Could someone test the branch `fix-copy-assets` as follows?

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@fix-copy-assets
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by peaceiris** [comment]
[Release actions-github-pages v3.7.1 · peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages/releases/tag/v3.7.1)

Thank you!
