### ISSUE TITLE
proposal: update node version to 20

### ISSUE THREAD

**Issue by oliver139** [peaceiris/actions-gh-pages#1062]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your proposal

According to the Github blog, actions using node 16 are deprecated. We should update this action to use node 20 asap.
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

### Describe the solution you'd like

Updating specify file like `.nvmrc` and `package.json` from using node 16 to node 20. Certainly, a test is needed to see if node 20 is working fine on the action.

**Comment by peaceiris** [comment]
Thanks.

**Comment by SukkaW** [comment]
@peaceiris Would you mind releasing a newer version under the v4 tag?
