### ISSUE TITLE
proposal: Please create a new release to include the Node 20 version bump

### ISSUE THREAD

**Issue by felixfontein** [peaceiris/actions-gh-pages#1070]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your proposal

Please create a new release that includes 4eb285e828117bca26638192c3ed309c622e7bad.

### Describe the solution you'd like

The last release was in March 2023, and since them quite a few dependencies were bumped. It would be helpful if a new release gets created.

### Describe alternatives you've considered

Referencing the commit directly, which is kind of ugly since it doesn't correspond to a version. (We reference versions by hash anyway, with the real version as a comment, and Dependabot updates that fine. But if you start referencing something else that doesn't have a version, Dependabot will likely no longer update the version comment, besides that comment either not being a version or being something else.)

**Comment by peaceiris** [comment]
ok

**Comment by felixfontein** [comment]
Any indication when such a release could happen?

**Comment by jonathan-4iTester** [comment]
@peaceiris, any news?

**Comment by Scc33** [comment]
Sorry to pile on... but any update?

**Comment by peaceiris** [comment]
Thanks all! Could you please try v4.0.0?

```yaml
- uses: peaceiris/actions-gh-pages@v4.0.0
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./public
```

**Comment by danivovich** [comment]
> Thanks all! Could you please try v4.0.0?
> 
> ```yaml
> - uses: peaceiris/actions-gh-pages@v4.0.0
>   with:
>     github_token: ${{ secrets.GITHUB_TOKEN }}
>     publish_dir: ./public
> ```
> 
> https://github.com/peaceiris/actions-gh-pages/releases/tag/v4.0.0

@peaceiris Worked well for my use case, no issues with the update, the action ran as expected.

**Comment by peaceiris** [comment]
Thanks!

The `v4.0.0` tag has been released and the `v4` tag is also available now!

https://github.com/peaceiris/actions-gh-pages/releases/tag/v4.0.0

**Comment by maxkratz** [comment]
> The `v4.0.0` tag has been released and the `v4` tag is also available now!
> 
> https://github.com/peaceiris/actions-gh-pages/releases/tag/v4.0.0

Thank you, the tag `v4` worked for me.

**Comment by BornToBeRoot** [comment]
Seems to work for me. Thanks!

**Comment by Scc33** [comment]
Works like a charm. Thanks!
