### ISSUE TITLE
Action failed with "Error: Error: Error: not found deploy key or tokens" on v3 but worked fine with v2

### ISSUE THREAD

**Issue by ajfriesen** [peaceiris/actions-gh-pages#123]
**Describe the bug**
I did update from v2.5.1to v3.2.0 and then my pipeline did not work anymore.

Error Message in the action:

```
Run peaceiris/actions-gh-pages@v3.2.0
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
[INFO] PublishBranch: gh-pages
[INFO] PublishDir: public
[INFO] ExternalRepository: 
[INFO] AllowEmptyCommit: false
[INFO] KeepFiles: false
[INFO] ForceOrphan: false
[INFO] UserName: 
[INFO] UserEmail: 
[INFO] CommitMessage: 
[INFO] TagName: 
[INFO] TagMessage: 
/usr/bin/git config --global gc.auto 0
/usr/bin/git config --global user.name ajfriesen
/usr/bin/git config --global user.email ajfriesen@users.noreply.github.com
##[error]Action failed with "Error: Error: Error: not found deploy key or tokens"
```

https://github.com/ajfriesen/ajfriesen.com/commit/359de152353df99186b723c9fa521968969d2f10

**To Reproduce**
1. Fork my repo and see if the deployment works

**Expected behavior**
I would have expected to work without any concern, after checking the changelog.

**Screenshots**

**Your YAML file**
- Repo Link: https://github.com/ajfriesen/ajfriesen.com
- Github action for this project: https://github.com/ajfriesen/ajfriesen.com/blob/master/.github/workflows/gh-pages.yml

**Additional context**
The error message does confuse me.
Just since before that I did a build with the same credentials and everything worked fine.
Then I saw that naming had changed to lower case and tried that as well, but still, no deploy key found error.
After that I just did delete my deploy key and secret and followed the instructions on your Readme but with same result.

I guess I am doing something wrong here.

**Comment by peaceiris** [comment]
```diff
- env
+ with
```

**Comment by ajfriesen** [comment]
Now I feel bad to not catch this small mistake on my own :-P
Thank you very much! 👍
