### ISSUE TITLE
Avoid to use `git config --global` for setting user name and email

### ISSUE THREAD

**Issue by nwtgck** [peaceiris/actions-gh-pages#151]
Thank you very much for the actions.

**Is your feature request related to a problem? Please describe.**
For setting committer information, currently `git config --global` is used. However, the command affects globally.

https://github.com/peaceiris/actions-gh-pages/blob/fd6e5fc7ce07cfd94a2311f7ac112bd797c3aee7/src/git-utils.ts#L106-L129

**Describe the solution you'd like**
`git commit --author="myname <myemail>" ...` This minimizes the effects.

**Describe alternatives you've considered**

**Additional context**

**Comment by peaceiris** [comment]
Thank you. That is my corner‐cutting. Do you have your implementation idea? Open your pr?

**Comment by peaceiris** [comment]
I will open my Pull Request.

**Comment by peaceiris** [comment]
Open #152
