### ISSUE TITLE
Publish Support

### ISSUE THREAD

**Issue by fishcharlie** [peaceiris/actions-gh-pages#227]
**Is your feature request related to a problem? Please describe.**

NA

**Describe the solution you'd like**

It'd be great if this package supported [Publish](https://github.com/JohnSundell/Publish).

**Describe alternatives you've considered**

Building my own custom package or running the commands manually myself.

**Additional context**

NA

**Comment by peaceiris** [comment]
Oh, I am a geek of Static Site Generators but I learned it for the first time!

Ok, I will investigate it and provide an example workflow.

**Comment by peaceiris** [comment]
Test repo: https://github.com/peaceiris/test-swift-publish
