### ISSUE TITLE
Prohibited branch detection does not work

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-gh-pages#245]
**Describe the bug**

When users set a `publish_branch` that is the same as a branch triggered by the workflow, this action stops the deployment to protect the branch.

https://github.com/peaceiris/actions-gh-pages/blob/e3404eb04b31f2987120c926fea07b0213caebd8/src/set-tokens.ts#L76-L81

Currently, this protection behavior does not work.

**To Reproduce**

With `peaceiris/actions-gh-pages@v3`

```yaml
on:
  push:
    branches:
      - master
...
          publish_branch: master
```

**Expected behavior**
This Action should return the error `You deploy from master to master`

**Screenshots**
<img width="464" alt="Screen Shot 2020-04-23 at 13 06 22" src="https://user-images.githubusercontent.com/30958501/80058107-5acf1a00-8563-11ea-9d9f-744b633c3311.png">

**Your YAML file**
- A link to your repository: https://github.com/peaceiris/test-mdbook
- A link to your YAML file: https://github.com/peaceiris/test-mdbook/actions/runs/85307348/workflow
- A link to your workflow log: https://github.com/peaceiris/test-mdbook/runs/610595170?check_suite_focus=true#step:6:116

**Additional context**
I found this bug in this article: [AsciidocのドキュメントをGitHub Actionsを用いてGitHub Pagesで公開する。 - Qiita](https://qiita.com/fake-deli-ca/items/1a946362e3d1993163e2#comments)

This protection should be also implemented for `personal_token`, `deploy_key`, and `eventName === 'pull_request'`.

**Comment by abedurftig** [comment]
Actually I want this to work. For user gh-pages the static code must be pushed to master. So, I have two repositories. Project A (the project that generates the static code in a workflow) and Project B which I want to push to in the workflow of Project A.

So I think when you use a `external_repository`, then this should be allowed.

**Comment by peaceiris** [comment]
@abedurftig See also https://github.com/peaceiris/actions-gh-pages/issues/318

**Comment by peaceiris** [comment]
@abedurftig Did you understand your mistake which is related to #318?

I found your [your workflow](https://github.com/abedurftig/personal-blog/commit/54757cb5b8602fa2af298f12fbe5f77d5b87a2a8#diff-21c07b469570a11985ad03102a1b3883) using `github_token` to deploy to an external repository. You should have used `personal_token`. Is the README unfriendly?

> README.md
>
> You can use deploy_key or `personal_token`. When you use `deploy_key`, set your private key to the repository which includes this action and set your public key to your external repository.
>
> Be careful, `GITHUB_TOKEN` has no permission to access to external repositories.

**Comment by abedurftig** [comment]
@peaceiris, thanks for following up. I see my mistake. I think the README is clear now.

**Comment by peaceiris** [comment]
It works well now.
