### ISSUE TITLE
upload of html generated with sphinx doesn't work

### ISSUE THREAD

**Issue by a-recknagel** [peaceiris/actions-gh-pages#26]
As described in https://github.com/a-recknagel/stenotype/issues/7, artifacts that when downloaded will render properly are faulty when served by gh-pages. I also tried [a different action](https://github.com/marketplace/actions/github-pages) that showed the same behaviour.

I tried building the docs with `html`, `singlehtml`, and `dirhtml`. All showed fine locally, and were broken when uploaded.

When checking my [gh-pages branch](https://github.com/a-recknagel/stenotype/tree/gh-pages), no files seem to have been omitted during the upload.

Any idea what could have gone wrong?

**Comment by peaceiris** [comment]
GitHub Pages does not read `_modules`, `_sources`, and `_static` (dir name starts with `_`)
**Please add `.nojekyll` file.**

```diff
      - name: Building documentation
        run: |
          pip install dist/*.whl
          pip install sphinx Pallets-Sphinx-Themes
          sphinx-apidoc --no-toc --module-first -o docs/autodoc src/stenotype
          sphinx-build docs public -b dirhtml
+         touch ./public/.nojekyll
      - name: github pages deploy
        uses: peaceiris/actions-gh-pages@v2.3.1
        env:
          PERSONAL_TOKEN: ${{ secrets.PAT }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: public
```

**Comment by a-recknagel** [comment]
Jup, works. Thanks for also finding the sphinx extension, either of them might be a good addition for the python example in your action readme, but as far as I'm concerned this issue is solved.

**Comment by peaceiris** [comment]
Thank you. I added about it. https://github.com/peaceiris/actions-gh-pages/commit/b16172a44df7b97706ba1b8df1f331af6216cf3b
