### ISSUE TITLE
Action passed with silent failure when no gh-pages branch existed

### ISSUE THREAD

**Issue by softprops** [peaceiris/actions-gh-pages#31]
Thanks for publishing this action.

I followed the readme instructions but ran into what may be a common but undocumented case.

I'm publishing for the first time and no gh-pages branch exists.

The action proceeds to stage changes but they never get pushed to my PUBLISH_BRANCH

```
Cloning into '/github/home/b8c542550a778e3eb0ca70abff3d5482'...
warning: Could not find remote branch gh-pages to clone.
fatal: Remote branch gh-pages not found in upstream origin
Initialized empty Git repository in /github/workspace/target/doc/.git/
Switched to a new branch 'gh-pages'
fatal: No such remote: 'origin'
INFO: Allowing empty commits: 
[gh-pages (root-commit) 975a973] Automated deployment: Sun Sep 22 04:26:54 UTC 2019 3a9dc85d243d35fe33b4992ae2a042c6793e8861
 131 files changed, 15230 insertions(+)
 create mode 100755 .lock
...more files...
```

My workflow step is configured with

```yaml
- name: Publish
        uses: docker://peaceiris/gh-pages:v2.3.1
        env:
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/doc
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by peaceiris** [comment]
Thank you. Please do not use `GITHUB_TOKEN` #9 
Try with `ACTIONS_DEPLOY_KEY` or `PERSONAL_TOKEN`

> [actions-gh-pages/README.md at 74f032c7e9f7be7e56320d6df9ca8707e104da12 · peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages/blob/74f032c7e9f7be7e56320d6df9ca8707e104da12/README.md#%EF%B8%8F-github_token)

**Comment by softprops** [comment]
I'll take a look. Thanks for the fast response. 

It may be worth documenting for users what permission the default github token is missing. Here's a list GitHub actions documents https://help.github.com/en/articles/virtual-environments-for-github-actions#github_token-secret. I realize these aren't enough to do everything but easy to miss for users of this action.

**Comment by peaceiris** [comment]
Thank you for your suggestion.

This is a bug of GitHub Pages and GitHub Actions. Read this: [Github action not triggering gh-pages upon push - GitHub Community Forum](https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869)

GitHub Actions team is investigating this problem.

**Comment by softprops** [comment]
Status update. This worked like a charm after generating a PERSONAL_TOKEN and setting `emptyCommits: true`
