### ISSUE TITLE
Github token results in Permission denied to github-actions

### ISSUE THREAD

**Issue by henryiii** [peaceiris/actions-gh-pages#319]
**Note that an issue which does not follow the template will be closed silently.**

### Check list before opening this issue

- [x] I read the latest README
  - I checked [Available Options](https://github.com/peaceiris/actions-gh-pages#options)
  - I followed [Tips and FAQ](https://github.com/peaceiris/actions-gh-pages#tips-and-faq)
  - I tried [Workflow Examples](https://github.com/peaceiris/actions-gh-pages#examples)

### Describe your question

I'm setting this up for a jupyterbook (new beta version). When I add this for the first time in a repo using GITHUB_TOKEN (normally I push across repos so have not been able to use the token method for actions-gh-pages before), I get the CI error:  "Permission to scikit-hep/scikit-hep-tutorials.git denied to github-actions". I've tried adding a gh-pages branch in the repo, and it doesn't change (mostly rerunning the action without a new commit). I do notice that:

```
/usr/bin/git remote rm origin
50
  fatal: No such remote: 'origin'
51
  [INFO] The process '/usr/bin/git' failed with exit code 128
```

Shows up earlier, but I don't think that's a problem, as it seems to continue after that. Here's the problem part:

```
/usr/bin/git push origin --force gh-pages
109
  remote: Permission to scikit-hep/scikit-hep-tutorials.git denied to github-actions[bot].
110
  fatal: unable to access 'https://github.com/scikit-hep/scikit-hep-tutorials.git/': The requested URL returned error: 403
111
  ##[error]Action failed with "The process '/usr/bin/git' failed with exit code 128"
```

I think this is likely a user error, but I don't see what I might have broken. The initial setup in the logs looks fine. I've tried the 3.5.9 version recommended in the [jupyter-book docs](https://jupyterbook.org/publish/gh-pages.html#automatically-host-your-book-with-github-actions), and the latest version.

### Link to your contents

- Repo: https://github.com/scikit-hep/scikit-hep-tutorials
- Workflow: https://github.com/scikit-hep/scikit-hep-tutorials/blob/master/.github/workflows/ci.yml
- Workflow run: https://github.com/scikit-hep/scikit-hep-tutorials/runs/700284075?check_suite_focus=true

### Screenshots

If applicable, add screenshots to help explain your question.

**Comment by peaceiris** [comment]
https://github.com/actions/checkout/issues/254

**Comment by henryiii** [comment]
Just my luck, perfect timing. :)

**Comment by peaceiris** [comment]
BTW, we probably need the `enable_jekyll: true` to make GitHub Pages read the files like `_images`. The demo site looks good but I recommend it.

I will open a pull-request to update [this page](https://jupyterbook.org/publish/gh-pages.html#automatically-host-your-book-with-github-actions) when GitHub becomes fine.

> Bypassing Jekyll makes the deployment faster and is necessary if you are deploying files or directories that start with underscores, since Jekyll considers these to be special resources and does not copy them to the final site. You only need to set `enable_jekyll` to true when you want to deploy a Jekyll-powered website and let GitHub Pages do the Jekyll processing.
>
> [Enable Built-in Jekyll - peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-enable-built-in-jekyll)

**Comment by henryiii** [comment]
The new Jupyter-book is based on Sphinx, the old one was based on Jekyll. Are you sure it's needed?

**Comment by henryiii** [comment]
PS: That's why the config file has a Jekyll-like name, but it's an artifact

**Comment by peaceiris** [comment]
Sorry, do not mind. I was waked up by many CI errors at midnight. I am so sleepy I misunderstood.

**Comment by jrappen** [comment]
https://www.githubstatus.com/ looks bad at the moment.

**Comment by peaceiris** [comment]
This issue was a temporary problem caused by the degradation of GitHub.

Thanks all for reporting!
