### ISSUE TITLE
"You deploy from master to master" error for organization type repository

### ISSUE THREAD

**Issue by padhia** [peaceiris/actions-gh-pages#363]
### Check list before opening this issue

- [ x] I read the latest README
  - I checked [Available Options](https://github.com/peaceiris/actions-gh-pages#options)
  - I followed [Tips and FAQ](https://github.com/peaceiris/actions-gh-pages#tips-and-faq)
  - I tried [Workflow Examples](https://github.com/peaceiris/actions-gh-pages#examples)
  - I read the latest GitHub Actions official documentation and learned the basic spec and concepts

### Describe your question

I have an organizational repo for which I am trying to publish Github pages. I followed [this document](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-repository-type---user-and-organization). The action fails with the error message mentioned in the title. I am not sure what am I doing wrong here.

### Link to your contents

Repo:  https://github.com/raas-garba/raas-garba.git
Workflow: https://github.com/raas-garba/raas-garba/blob/master/.github/workflows/pages.yml

**Comment by peaceiris** [comment]
Your operation will break your content. You can use the `gh-pages` branch to deploy your site instead of the `master` branch.

**Comment by padhia** [comment]
Thanks for the quick response. Of course, I don't want my source code to be overwritten by the generated  HTML. Mine is an *Organization Type* repository. Maybe I am missing something, [**this**](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-repository-type---user-and-organization) example uses `master` branch in the documentation. Is publishing repository name not automatically derived as `<repo>.github.io`? Do I need to specify that as an external repo?

**Comment by peaceiris** [comment]
You have two ways:

1. Deploy your site from `raas-garba/raas-garba` to `raas-garba/raas-garba.github.io` using the `external_repository` option
1. Move the master branch of `raas-garba/raas-garba` to another branch of `raas-garba/raas-garba.github.io` (e.g. `source` branch)

**Comment by padhia** [comment]
That fixed it. Thanks!
