### ISSUE TITLE
Failure to deploy when branch already exists

### ISSUE THREAD

**Issue by jeluard** [peaceiris/actions-gh-pages#368]
### Describe your question

When the action runs for the second time, it fails because the branch already exists. I tried to find relevant past issues but they don't apply apparently. My config is pretty simple and follows your guidelines. See it here: https://github.com/paritytech/substrate-playground/blob/develop/.github/workflows/book.yml#L33

### Link to your contents

You can find the failing run here: https://github.com/paritytech/substrate-playground/runs/806625940?check_suite_focus=true

**Comment by peaceiris** [comment]
Your `publish_dir` is wrong.

```diff
- publish_dir: ./docs/book/html
+ publish_dir: ./docs/book
```

**Comment by jeluard** [comment]
Ooh yes you are right. Not sure how I got it working in the first place..

Thanks!!
