### ISSUE TITLE
Question: Difference between GITHUB_TOKEN & PERSONAL_TOKEN

### ISSUE THREAD

**Issue by vella-nicholas** [peaceiris/actions-gh-pages#41]
What is the difference between the two? For GITHUB_TOKEN I did not need to add it to "Secrets" and the workflow works fine.

**Comment by peaceiris** [comment]
> `GITHUB_TOKEN` secret
>
> The `GITHUB_TOKEN` secret is a GitHub App installation token scoped to the repository that contains your workflow. GitHub creates the `GITHUB_TOKEN` secret for you by default, but you must include it in your workflow file in order for actions to use it. You can use the `GITHUB_TOKEN` secret to make authenticated GitHub API calls on behalf of an action.

- [Virtual environments for GitHub Actions - GitHub Help](https://help.github.com/en/articles/virtual-environments-for-github-actions#github_token-secret)

We can use `GITHUB_TOKEN` by default without setting up. Currently, `GITHUB_TOKEN` works only on a **private** repository. See #9 

We can use `PERSONAL_TOKEN` that is generated at [Personal Access Tokens](https://github.com/settings/tokens) with `repo` scope. It works well on private and public repositories.

In the future, it is desirable to use `GITHUB_TOKEN` on all repositories. But the token has some problems with permissions between GitHub Pages and GitHub Actions. GitHub support team is investigating it and we are waiting for a good reply from them.

**Comment by vella-nicholas** [comment]
Thank you for the very detailed explanation.
