### ISSUE TITLE
Parameter for keeping only last commit in `gh-pages`

### ISSUE THREAD

**Issue by ruzickap** [peaceiris/actions-gh-pages#42]
Hello.

Would it be possible to implement some parameter which will keep only the last commit for the `gh-pages` containing generated HTML files?

-> I do not want to keep the "standard" commit history for HTML pages (`gh-pages`) - therefore some parameter which will keep only the last commit (with last HTML pages) may be handy.

**Comment by peaceiris** [comment]
It is possible. I opened #43
