### ISSUE TITLE
Error: Action failed with "The process '/usr/bin/git' failed with exit code 128"

### ISSUE THREAD

**Issue by WuZhuoran** [peaceiris/actions-gh-pages#497]
### Check list before opening this issue

- [x] I read the latest README
- [x] I checked [Available Options](https://github.com/peaceiris/actions-gh-pages#options)
- [x] I followed [Tips and FAQ](https://github.com/peaceiris/actions-gh-pages#tips-and-faq)
- [x] I tried [Workflow Examples](https://github.com/peaceiris/actions-gh-pages#examples)
- [x] I read the latest GitHub Actions official documentation and learned the basic spec and concepts

### Describe your question

First time to use this action to deploy one website.
The website is build with [Hugo](https://gohugo.io/) and I want to use actions to do auto deploy on repo github pages.
The action will fail at `Deploy` stage.

The error message is:

```
Run peaceiris/actions-gh-pages@v3
Dump inputs
Setup auth token
Prepare publishing assets
Setup Git config
Create a commit
Push the commit or tag
  /usr/bin/git push origin gh-pages
  remote: Permission to YiGu-Studio/DocsModdingBannerlordCN.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/YiGu-Studio/DocsModdingBannerlordCN.git/': The requested URL returned error: 403
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 128"
```

I tried with `github_token: ${{ secrets.GITHUB_TOKEN }}`
it will throw the error above.

I tried with `personal_token: ${{ secrets.PERSONAL_TOKEN }}` or `deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}`
it will failed at stage `Setup auth token`

I even tried with change username and email to my account name. But it still failed.

I post the screen shots of my secrets page in next section.

### Link to your contents

Here is the workflow files.
https://github.com/YiGu-Studio/DocsModdingBannerlordCN/blob/e64547ca8ae8ed77e617ecdf816239de051d3273/.github/workflows/hugo_deploy.yml

The raw log of the workflow is here.
https://pipelines.actions.githubusercontent.com/ReJNjsa4JNo8v6DjAI5NX8yN0RMO8ccdvpMUIOf1CGkDAThal5/_apis/pipelines/1/runs/21/signedlogcontent/3?urlExpires=2020-10-03T00%3A36%3A55.9686007Z&urlSigningMethod=HMACV1&urlSignature=7APdckxxT5kF2pDqog6wZtlzjwFxDteZZa8iGBLsRwE%3D

### Screenshots

![Screen Shot 2020-10-02 at 5 34 28 PM](https://user-images.githubusercontent.com/8717187/94979062-891f3100-04d5-11eb-8f3a-7800c6c37005.png)

If using Personal Token or Deploy Key
![Screen Shot 2020-10-02 at 5 46 56 PM](https://user-images.githubusercontent.com/8717187/94979412-4cecd000-04d7-11eb-86e9-e5ad7533a05e.png)

### Additional context

I found that if I directly push to branch. it will pass.
But Now I want this to be used for all PR.

**Double checked. If I merge this PR, the run will run successfully, but it will failed in PR.**

**Comment by WuZhuoran** [comment]
Fixed by recreating the API Deploy KEY.

**Comment by peaceiris** [comment]
This may be related to #339.

https://github.com/peaceiris/actions-gh-pages/issues/339#issuecomment-639546151
https://github.com/peaceiris/actions-gh-pages/issues/339#issuecomment-639546151
