### ISSUE TITLE
  Error: Action failed with "ENOENT: no such file or directory, scandir '/home/public'"

### ISSUE THREAD

**Issue by elbaulp** [peaceiris/actions-gh-pages#502]
### Check list before opening this issue

- [X] I read the latest README
  - I checked [Available Options](https://github.com/peaceiris/actions-gh-pages#options)
  - I followed [Tips and FAQ](https://github.com/peaceiris/actions-gh-pages#tips-and-faq)
  - I tried [Workflow Examples](https://github.com/peaceiris/actions-gh-pages#examples)
  - I read the latest GitHub Actions official documentation and learned the basic spec and concepts

### Describe your question

I am using emacs org-mode to generate a static blog. At first this actions worked fine, it got the contents from the public directory and publish them, but since a few days I am getting this error:

> Error: Action failed with "ENOENT: no such file or directory, scandir '/home/public'"

I am unable to find which change I made that cause that problem. 

### Link to your contents

Here is the output of the failing action:
 - https://github.com/elbaulp/elbaulp.github.io/runs/1213144010
- [My Dockerfile](https://github.com/elbaulp/elbaulp.github.io/blob/master/Dockerfile)
- [My workflow](https://github.com/elbaulp/elbaulp.github.io/blob/master/.github/workflows/publish.yml)
What I am doing is creating a custom action with my own Dockerfile, which runs emacs as batch mode and generate the static site, then I use this action to publish to `gh-pages`

### Screenshots

Here is the full stacktrace:

```
  [INFO] ForceOrphan: true
  [INFO] chdir /home/runner/actions_github_pages_1601964322176
  /usr/bin/git init
  Initialized empty Git repository in /home/runner/actions_github_pages_1601964322176/.git/
  /usr/bin/git checkout --orphan gh-pages
  Switched to a new branch 'gh-pages'
  [INFO] prepare publishing assets
  Error: Action failed with "ENOENT: no such file or directory, scandir '/home/public'"
```

Any idea? I've been struggling with this error a few days now, it's like if the public folder got removed or something, but somehow it worked before.

**Comment by peaceiris** [comment]
This is a general question about creating a GitHub Action. [Latest GitHub Actions topics - GitHub Support Community](https://github.community/c/github-actions/41) is a good place for this. (recommended)

My advice: Why don't you use the `${GITHUB_WORKSPACE}/public` in your script (`build.sh`)?

cf. [actions-gh-pages/entrypoint.sh at v2 · peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages/blob/v2/entrypoint.sh)

**Comment by elbaulp** [comment]
Thanks, will investigate further and try your tips
