### ISSUE TITLE
Action failed with "ENOENT: no such file or directory with force_orphan

### ISSUE THREAD

**Issue by letmaik** [peaceiris/actions-gh-pages#523]
### Describe the bug

I'm trying to deploy the repo root but it fails:
```
Switched to a new branch 'gh-pages'
  [INFO] prepare publishing assets
  [INFO] delete .git
  [INFO] copy /home/runner/work/chip8/chip8/ to /home/runner/actions_github_pages_1602884889152
  [INFO] delete excluded assets
  [INFO] delete /home/runner/actions_github_pages_1602884889152/.github
  Error: Action failed with "ENOENT: no such file or directory, realpath '/home/runner/actions_github_pages_1602884889152/.github/workflows'"
```

### To Reproduce

https://github.com/letmaik/chip8/runs/1266688809?check_suite_focus=true

### Expected behavior

Should not fail with default settings.

### Your YAML file

https://github.com/letmaik/chip8/blob/master/.github/workflows/gh-pages.yml

**Comment by peaceiris** [comment]
Thanks.

This is a problem related to the `force_orphan` option (See also #522 )

By deleting the line as follows, your workflow will work well, I think.

```diff
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
-        force_orphan: true
```

**Comment by ddeboer** [comment]
It also breaks when `force_orphan` is _not_ set to `true`: https://github.com/netwerk-digitaal-erfgoed/requirements-template/runs/1279392636?check_suite_focus=true#step:5:21, with:

`
/usr/bin/git rm -r --ignore-unmatch *
41
  rm '.nojekyll'
42
  rm 'Makefile'
43
  rm 'README.md'
44
  rm 'index.bs'
45
  rm 'index.html'
46
  [INFO] chdir /home/runner/actions_github_pages_1603176299609
47
  [INFO] prepare publishing assets
48
  [INFO] delete .git
49
  [INFO] copy /home/runner/work/requirements-template/requirements-template/ to /home/runner/actions_github_pages_1603176299609
50
  cp: copyFileSync: could not write to dest file (code=EACCES):/home/runner/actions_github_pages_1603176299609/.git/objects/d6/e50d743451b0474887a69d7181d4aebc7ca1fd
51
  cp: cannot create directory '/home/runner/actions_github_pages_1603176299609': No such file or directory
52
  [INFO] delete excluded assets
53
  [INFO] Created /home/runner/actions_github_pages_1603176299609/.nojekyll
`

**Comment by peaceiris** [comment]
@ddeboer Could you try d929bb9?

```yaml
      - name: Publish HTML to GitHub Pages
        uses: peaceiris/actions-gh-pages@d929bb9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
```

**Comment by ddeboer** [comment]
Unfortunately that gives the same error: https://github.com/netwerk-digitaal-erfgoed/requirements-template/runs/1279644649?check_suite_focus=true

To be clear: the workflow ‘succeeds’ (is green), but because of the above error the GitHub Pages output is not updated. 

I’m guessing this has to do with `publish_dir: ./`, because the root dir contains the `.git` dir while subdirs (`public/` for instance) don’t.

**Comment by peaceiris** [comment]
ok, How about ed9896e? https://github.com/peaceiris/actions-gh-pages/pull/528

**Comment by peaceiris** [comment]
The `v3.7.3` has been released and the v3 tag update. I expect it will work well on your workflow.

**Comment by peaceiris** [comment]
I close this. If there is still something wrong, let me know here (if it is related to this.) or create another issue. Thank you.
