### ISSUE TITLE
Large site deployments fail (probably due to undocumented limit of size of a single commit)

### ISSUE THREAD

**Issue by cmahnke** [peaceiris/actions-gh-pages#532]
### Describe the bug
I have a fairly large Hugo site (locally generated it's about 3.5 GB) and it's not possible to deploy it:

```
 /usr/bin/git push origin --force gh-pages
  error: RPC failed; curl 55 Failed sending data to the peer
  fatal: the remote end hung up unexpectedly
  fatal: the remote end hung up unexpectedly
  Everything up-to-date
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 1"
```

### To Reproduce

Create a site that contains a lot of generated date like images

### Expected behavior

The Hugo site should be deployed.

### Screenshots

Doesn't apply.

### Your YAML file

* https://github.com/cmahnke/blaufusstoelpel/blob/main/.github/workflows/gh-pages.yml

### Additional context

I have similar issues before (from my local machine to GitHub), but wasn't sure if it's related to the size of a **commit** or a **push**, now it seems that this distinction doesn't really matter. Maybe it would help if there would be a parameter `chunkSize` which would stop adding files if a chuck size of let's say 1 Gig is reached, do a **commit and push** and resume afterwards, committing and pushing the next chunk.

**Comment by peaceiris** [comment]
It's time to migrate to another paid hosting service.

> Usage limits
> GitHub Pages sites are subject to the following usage limits:
> GitHub Pages source repositories have a recommended limit of 1GB. For more information, see "What is my disk quota?"
> 

https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages
