### ISSUE TITLE
The Action Did Not Put The Gatsby Generated Files In The gh-pages branch

### ISSUE THREAD

**Issue by Skillz4Killz** [peaceiris/actions-gh-pages#536]
### Check list before opening this issue

- [x] I read the latest README
  - I checked [Available Options](https://github.com/peaceiris/actions-gh-pages#options)
  - I followed [Tips and FAQ](https://github.com/peaceiris/actions-gh-pages#tips-and-faq)
  - I tried [Workflow Examples](https://github.com/peaceiris/actions-gh-pages#examples)
  - I read the latest GitHub Actions official documentation and learned the basic spec and concepts

### Describe your question

The action although failed at first with a malicious error warning due to an outdated dep, i was able to update it and it all worked. The action passes but the files are not generated in the gh-pages branch

### Link to your contents

- https://github.com/Skillz4Killz/Discordeno/
- https://github.com/Skillz4Killz/Discordeno/blob/next/.github/workflows/gatsby.yml
- https://github.com/Skillz4Killz/Discordeno/tree/gh-pages

### Screenshots

![image](https://user-images.githubusercontent.com/23035000/99578952-8ad08580-29ab-11eb-8f33-1a9ae0a109d7.png)

![image](https://user-images.githubusercontent.com/23035000/99578986-9754de00-29ab-11eb-9892-82220bfe33c4.png)

### Additional context

N/A

**Comment by peaceiris** [comment]
check your publishing directory
`publish_dir: ./docs/public`

**Comment by Skillz4Killz** [comment]
@peaceiris Thank you that did solve the issue of the missing files but i think something is still missing. 

This is the one that the action generates to GH Pages https://discordeno.js.org/

This is the one thats hosted on netlify, the exact same code https://discordeno.netlify.app

It looks like some css files are missing from gh pages files that the action generated

**Comment by peaceiris** [comment]
You have seemed to change some settings.

My fork: https://github.com/peaceiris/Discordeno
My site: https://test-discordeno.peaceiris.com/

It works well. Can we close this? @Skillz4Killz

**Comment by Skillz4Killz** [comment]
Since switched over to Vuepress, sadly wasn't able to get it working right.

Thank you nonetheless. Much appreciated.
