### ISSUE TITLE
Error using GITHUB_TOKEN for deployment

### ISSUE THREAD

**Issue by calumshep** [peaceiris/actions-gh-pages#537]
### Check list before opening this issue

- [x] I read the latest README
  - I checked [Available Options](https://github.com/peaceiris/actions-gh-pages#options)
  - I followed [Tips and FAQ](https://github.com/peaceiris/actions-gh-pages#tips-and-faq)
  - I tried [Workflow Examples](https://github.com/peaceiris/actions-gh-pages#examples)
  - I read the latest GitHub Actions official documentation and learned the basic spec and concepts

### Describe your question

Action failed using `${{ secrets.GITHUB_TOKEN }}" with the error:
```
Error loading key "/home/runner/.ssh/github": invalid format
Error: Action failed with "The process '/usr/bin/ssh-add' failed with exit code 1"
```
I've since got it to work generating my own key for deployment but I couldn't get it to work with the token on a push event.

### Link to your contents

Workflow file: https://github.com/Watt-Dev/home/blob/794ac1f4caf201edc9abae40a49d6e19c991093c/.github/workflows/deploy.yml
Raw Actions output log: https://pipelines.actions.githubusercontent.com/F96ukYcl0J3LN4cTtPBBkzzgashqekjPLF3VXklmDM2MXuwpfZ/_apis/pipelines/1/runs/14/signedlogcontent/3?urlExpires=2020-11-20T16%3A44%3A33.6310821Z&urlSigningMethod=HMACV1&urlSignature=E0tVQJX%2B1u6GKZiyYI7B815shwimQ0fujMNWRNvz6OU%3D

**Comment by peaceiris** [comment]
Please read the README.md first.

```diff
- deploy_key: ${{ secrets.GITHUB_TOKEN }}
+ github_token: ${{ secrets.GITHUB_TOKEN }}
```
