### ISSUE TITLE
Update sample yaml to setup-node@v2.1.2

### ISSUE THREAD

**Issue by dan-mba** [peaceiris/actions-gh-pages#542]
### Describe the bug

A GitHub security issue forced changes to setup-node action.
Running the setup-node action with a version below 2.1.2 will fail.
Error Messages:
`Unable to process command '::add-path::/opt/hostedtoolcache/node/12.19.0/x64/bin' successfully.`
`The add-path command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the ACTIONS_ALLOW_UNSECURE_COMMANDS environment variable to true.`

### To Reproduce

Run sample yaml ( I used the Gatsby )

### Expected behavior

Action to run

### Additional context

[GitHub Blog on security issue](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)

**Comment by peaceiris** [comment]
Thank you!
