### ISSUE TITLE
new file is not being built.

### ISSUE THREAD

**Issue by jkotra** [peaceiris/actions-gh-pages#586]
### Check list before opening this issue

- [x] I read the latest README
  - I checked [Available Options](https://github.com/peaceiris/actions-gh-pages#options)
  - I followed [Tips and FAQ](https://github.com/peaceiris/actions-gh-pages#tips-and-faq)
  - I tried [Workflow Examples](https://github.com/peaceiris/actions-gh-pages#examples)
  - I read the latest GitHub Actions official documentation and learned the basic spec and concepts

### Describe your question

i added new post / file to my blog. upon pushing it, CI is using correct commit but hugo is not building / considering new post.

### Link to your contents

https://github.com/jkotra/jkotra.github.io
https://github.com/jkotra/jkotra.github.io/runs/2134160390?check_suite_focus=true
https://github.com/jkotra/jkotra.github.io/actions/runs/662284724/workflow

### Additional context

it does correctly checkout into `'51cd5137e448891a3f09b56e93d4fc801c3ee89d'` and that commit does contain new file. but for whatever reason hugo is not building that.

```
Start building sites … 

                   | EN  
-------------------+-----
  Pages            | 61  
  Paginator pages  |  3  
  Non-page files   | 17  
  Static files     |  7  
  Processed images |  0  
  Aliases          |  1  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 246 ms
```

it's stuck at that (61 pages) no matter how many pages i add.

hope someone can help me out here.

**Comment by peaceiris** [comment]
Check date. We can run the `date` command to check the timezone on the GitHub Actions runner. Also `hugo --buildFuture` can build posts with date in the future.

**Comment by jkotra** [comment]
> Check date. We can run the `date` command to check the timezone on the GitHub Actions runner. Also `hugo --buildFuture` can build posts with date in the future.


thanks :+1: , that seems to be the problem. i changed the date on my new post to a day before and it's now working as expected.

also would like to apologize for stating issue in wrong(but related) repository.
