### ISSUE TITLE
SSH deploy fails without ACTIONS_ALLOW_UNSECURE_COMMANDS enabled

### ISSUE THREAD

**Issue by krmax44** [peaceiris/actions-gh-pages#588]
### Describe the bug

Without the env variable `ACTIONS_ALLOW_UNSECURE_COMMANDS` set to `true`, the deploy fails:
https://github.com/okfde/transparenzranking.de/runs/2191485565#step:7:33

### To Reproduce

Deploy using an SSH key. See YAML below.

### Your YAML file

https://github.com/okfde/transparenzranking.de/commit/ee0fd6a725ab79df93603340fd8842d171a617eb

### Additional context

Some suggested that setup-node below a certain version might have to do with this. To my knowledge, it's using the latest version.

**Comment by peaceiris** [comment]
See the repository name carefully 👍 

```diff
- peaceiris/actions-github-pages
+ peaceiris/actions-gh-pages
```

The former is a prototype. (Archived project)

**Comment by krmax44** [comment]
Shoot, thanks for the heads up! :)
