### ISSUE TITLE
Tag v3 hasnt been updated to tag v3.8

### ISSUE THREAD

**Issue by WtfJoke** [peaceiris/actions-gh-pages#590]
### Describe the bug
Tag v3 havent been updated to v3.8

### To Reproduce
Dependabot issued https://github.com/xxlsonnenschirm/xxlsonnenschirm.github.io/pull/2

### Expected behavior
I expect that v3 reflects latest changes, eg resolves to v3.8

**Comment by peaceiris** [comment]
I just forgot to make the draft release published. The v3 tag has been updated now. Thank you for reporting!

https://github.com/peaceiris/actions-gh-pages/releases/tag/v3.8.0

**Comment by WtfJoke** [comment]
Thank you, that was exceptionally fast
