### ISSUE TITLE
Publishing assets fails with "cp: cannot create directory"

### ISSUE THREAD

**Issue by peschee** [peaceiris/actions-gh-pages#591]
### Describe the bug

I have the following in my Github Actions config:

```yaml
- name: Deploys
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./storybook-static
    allow_empty_commit: true
```

Until recently, the publishing to gh-pages worked perfectly. Now, I'm getting the following error in the "Prepare publishing assets" phase of the action:

```
  [INFO] copy /home/runner/work/portal-components/portal-components/storybook-static to /home/runner/actions_github_pages_1617177227961
  cp: cannot create directory '/home/runner/actions_github_pages_1617177227961': No such file or directory
```

Full output is:

```
Prepare publishing assets
  [INFO] ForceOrphan: false
  /usr/bin/git clone --depth=1 --single-branch --branch gh-pages ***github.com/inventage/portal-components.git /home/runner/actions_github_pages_1617177227961
  Cloning into '/home/runner/actions_github_pages_1617177227961'...
  [INFO] clean up /home/runner/actions_github_pages_1617177227961
  [INFO] chdir /home/runner/actions_github_pages_1617177227961
  /usr/bin/git rm -r --ignore-unmatch *
  rm '.nojekyll'
  rm '21bc7de4.js'
  rm '48ed5318.js'
  rm 'custom-elements.json'
  rm 'data/data-settings.json'
  rm 'data/data.json'
  [INFO] chdir /home/runner/actions_github_pages_1617177227961
  [INFO] prepare publishing assets
  [INFO] copy /home/runner/work/portal-components/portal-components/storybook-static to /home/runner/actions_github_pages_1617177227961
  cp: cannot create directory '/home/runner/actions_github_pages_1617177227961': No such file or directory
  [INFO] delete excluded assets
  rm: no paths given
  [INFO] Created /home/runner/actions_github_pages_1617177227961/.nojekyll
```

### To Reproduce

1. Go to https://github.com/inventage/portal-components/runs/2234944681?check_suite_focus=true
2. In the console output, click on "Deploys" → "Prepare publishing assets"
3. The published page should be here: https://inventage.github.io/portal-components/; the gh-pages branch (https://github.com/inventage/portal-components/tree/gh-pages) is missing the necessary files for the deployment to work

### Expected behavior

The documentation should be published at https://inventage.github.io/portal-components/

### Your YAML file

- https://github.com/inventage/portal-components/blob/main/.github/workflows/main.yml#L105

**Comment by peaceiris** [comment]
Thank you for reporting! I confirmed the reproducibility by myself. I will investigate this more deeply.

**Comment by peaceiris** [comment]
I got it. Please check the generating process of the `test-data.json`. The following workaround will fix the deployment.

```yaml
      - name: Build
        run: npm run build

      - run: |
          cd storybook-static/data
          unlink test-data.json
          ln -s ../../components/portal-navigation/test/test-data.json test-data.json
```

This action failed to catch this type of error.

**Comment by peschee** [comment]
`test-data.json` is a symbolic link to a subfolder that might not be uploaded to gh-pages, thanks for catching that!

So this is not a bug in your action.
