### ISSUE TITLE
setting public_dir to current direcotry "." does not work.

### ISSUE THREAD

**Issue by Fenn-CS** [peaceiris/actions-gh-pages#598]
### Describe the bug
Setting `public_dir` to `.` or `./` does not work.

### To Reproduce

Set `public_dir` to `.` or `./` 

### Expected behavior

Publish files in runner directory

### Screenshots
Copy fails, empty folder published.

### Your YAML file

https://github.com/phpList/swagger-ui/blob/master/.github/workflows/github-pages.yml

**Comment by peaceiris** [comment]
You added this action without actions/checkout. https://github.com/phpList/swagger-ui/commit/0b9317288907d296e072e8d5369f985eaad3f279#diff-983e80aff18936dd64301171c8eec0d019a56ed0e2849985c5ba1c7cb48a8607

**Comment by Fenn-CS** [comment]
@peaceiris thank you.
