### ISSUE TITLE
proposal: tag the latest release with major version

### ISSUE THREAD

**Issue by sarisia** [peaceiris/actions-gh-pages#60]
**Is your feature request related to a problem? Please describe.**
Could you please tag the latest release with major version (`v2` here) ?
With major version tag we can always use the latest action without breaking changes and can specify this action as described in the official document:

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsuses

**Describe the solution you'd like**
Tag the latest release with `v2` tag

**Comment by peaceiris** [comment]
v2 tag was created.

**Comment by sarisia** [comment]
thanks a lot!
