### ISSUE TITLE
Failed push: '/usr/bin/git' failed with exit code 1

### ISSUE THREAD

**Issue by jlumbroso** [peaceiris/actions-gh-pages#605]
### Describe the bug

The action terminates with the following error:
```
Push the commit or tag
  /usr/bin/git push origin gh-pages
  To https://github.com/mbraverm/mbraverm.github.io.git
   ! [rejected]        gh-pages -> gh-pages (fetch first)
  error: failed to push some refs to 'https://github.com/mbraverm/mbraverm.github.io.git'
  hint: Updates were rejected because the remote contains work that you do
  hint: not have locally. This is usually caused by another repository pushing
  hint: to the same ref. You may want to first integrate the remote changes
  hint: (e.g., 'git pull ...') before pushing again.
  hint: See the 'Note about fast-forwards' in 'git push --help' for details.
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 1"
```

### To Reproduce

I have not figured out how to reproduce. The only thing I have instead is the full log of the workflow when it crashed (and it is the only time it did not work).

Here is the GitHub Actions page:
https://github.com/mbraverm/mbraverm.github.io/actions/runs/715953965

And here is the full text log:
https://gist.github.com/jlumbroso/ec03e27149243442bd0148403f870ec1

### Expected behavior

It is unclear why the `git` push was unsuccessful. I expected the push to be successful.

### Your YAML file

The repository is [https://github.com/mbraverm/mbraverm.github.io](https://github.com/mbraverm/mbraverm.github.io).

The YAML file of the GitHub Actions workflow that triggered this [is available here](https://github.com/mbraverm/mbraverm.github.io/blob/a02e4e768f8dd131f5aa746b1713c2c562f43c7d/.github/workflows/gh-pages.yaml).

### Additional context

The [commit associated with the workflow that didn't work](https://github.com/mbraverm/mbraverm.github.io/commit/5cbe3af304391e7175496028cc5a2fd20a38ce2e) was the deletion of an empty file (`/static/media/Dynamical-Systems/1`).

**Comment by peaceiris** [comment]
- Sun, 04 Apr 2021 05:37:02 GMT `git push` by the previous run https://github.com/mbraverm/mbraverm.github.io/runs/2262951883#step:8:209
- Sun, 04 Apr 2021 05:37:04 GMT `git clone` by the failed run https://github.com/mbraverm/mbraverm.github.io/runs/2262952863?check_suite_focus=true#step:8:37
- Sun, 04 Apr 2021 05:37:06 GMT `git push` by the failed run https://github.com/mbraverm/mbraverm.github.io/runs/2262952863?check_suite_focus=true#step:8:210

The two jobs have started in a short span of time. The failed run may have run `git clone` before the Git server reflects the latest push, I think.

**Comment by jlumbroso** [comment]
Many thanks for taking a look @peaceiris, and that sounds like a likely explanation. I am closing this issue. Thanks again for your wonderful GitHub Actions!
