### ISSUE TITLE
Action failed with "The process '/usr/bin/git' failed with exit code 1"

### ISSUE THREAD

**Issue by Ayaoayao** [peaceiris/actions-gh-pages#611]
### Check list before opening this issue

- [x] I read the latest README
  - I checked [Available Options](https://github.com/peaceiris/actions-gh-pages#options)
  - I followed [Tips and FAQ](https://github.com/peaceiris/actions-gh-pages#tips-and-faq)
  - I tried [Workflow Examples](https://github.com/peaceiris/actions-gh-pages#examples)
  - I read the latest GitHub Actions official documentation and learned the basic spec and concepts

### Describe your question

After add `hasCJKLanguage: true` to the HUGO configuration yaml. The GitHub action failed at pushing refs back to `gh-pages` branch.

### Link to your contents

- Repo: 
   https://github.com/Ayaoayao/Ayaoayao.github.io
- Workflows: 
  https://github.com/Ayaoayao/Ayaoayao.github.io/actions/runs/847176041

### Additional context

I tried it 3 times and all of them failed at the same action.

**Comment by tobihagemann** [comment]
Having the same error message and I didn't even change much. The diff is miniscule.

https://github.com/cryptomator/cryptomator.github.io/runs/2594443604

Maybe something else is wrong?

**Comment by amousset** [comment]
Could be linked to availability issues on pages and actions today https://www.githubstatus.com/

**Comment by Blamas** [comment]
> 
> 
> Could be linked to availability issues on pages and actions today https://www.githubstatus.com/

Seems to be that, got the same error, tried to revert and still got the same error.

**Comment by tobihagemann** [comment]
That was probably it. Seems to be fixed.

**Comment by Ayaoayao** [comment]
Thanks everyone and seems that the root cause is just as @amousset mentioned. I will close this issue.
