### ISSUE TITLE
Exclude Assets (Resolved)

### ISSUE THREAD

**Issue by KurtBruns** [peaceiris/actions-gh-pages#615]
@peaceiris Yesterday I commented on issue #163 about having trouble with the `exclude_assets` option and you asked me to submit a new issue.

Since then, I got the `exclude_assets` option to work as expected. The mistake was on my end and trivial. Thanks for you prompt response!

**Comment by peaceiris** [comment]
That's great! Thank you for the reply, Have a good day ;)
