### ISSUE TITLE
Ability to update symbolic link to destination_dir 

### ISSUE THREAD

**Issue by djhoese** [peaceiris/actions-gh-pages#617]
### Is your feature request related to a problem? Please describe

I have a sphinx project (Python) where I'm using this action to publish the docs in both a "latest" `destination_dir` and a separate step that uses this action on releases where the tag name (ex. `v0.1.0`) is used as the `destination_dir`. It would be nice to have a symbolic link that this action could automatically update to point to the `destination_dir` so going to `https://mysite.github.io/stable` would go to whatever the newest release's documentation is.

If something like this is already possible with this action, sorry.

### Describe the solution you'd like

Something like a `destination_symlink` option that could be set to the directory name.

### Describe alternatives you've considered

I've thought about structuring my publish_dir in a way that it already includes the symbolic link and a sub-directory representing the `destination_dir` and then maybe use `keep_files` so any existing versioned directories would remain in the repository. I'm not sure this would work and seems error prone.

I've also thought about doing a post-deploy step in my workflow that clones the repository, updates the link, and then pushes it but at that point I'm not really using this action at all.

I could also do this manually after every release, but that's no fun.

**Comment by peaceiris** [comment]
In general, Static Site Generators can implement a multi-version website with an internal function or an extension. Did you try the following extensions?

- [sphinx-contrib/sphinxcontrib-versioning: Sphinx extension that allows building versioned docs for self-hosting.](https://github.com/sphinx-contrib/sphinxcontrib-versioning)
- [Holzhaus/sphinx-multiversion: Sphinx extension for building self-hosted versioned docs.](https://github.com/Holzhaus/sphinx-multiversion)

If the extensions do not satisfy your demand, you can implement it by improving your YAML workflow.

**Comment by peaceiris** [comment]
Also, [Read the Docs](https://docs.readthedocs.io/en/stable/) is good for your case, I think.

[Versioned Documentation — Read the Docs 5.17.0 documentation](https://docs.readthedocs.io/en/stable/versions.html)

**Comment by djhoese** [comment]
I use readthedocs for a lot of projects, but the two projects I'm working with right now are a little complex for RTD to build and host. I tried to use sphinx-multiversion for one of my projects but ran into issues since the source files were in a separate git submodule from the repository doing the generation (there's an issue on the sphinx-multiversion repos). I'll have to look as sphinxcontrib-versioning.

Thanks.
