### ISSUE TITLE
Some files not being copied over to `gh-pages` branch

### ISSUE THREAD

**Issue by pommevilla** [peaceiris/actions-gh-pages#625]
### Check list before opening this issue

- [x] I read the latest README
- [x] I checked [Available Options](https://github.com/peaceiris/actions-gh-pages#options)
- [x] I followed [Tips and FAQ](https://github.com/peaceiris/actions-gh-pages#tips-and-faq)
- [x] I tried [Workflow Examples](https://github.com/peaceiris/actions-gh-pages#examples)
- [x] I read the latest GitHub Actions official documentation and learned the basic spec and concepts

### Describe your question

I've created a workflow that renders documents and uses `action-gh-pages` to push the new pages to a site. The workflow is [here](url) and the finished site with the proper html is [here](https://pommevilla.github.io/friendly-dollop/). I've used this same workflow in a [different repo](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/main/.github/workflows/quarto-render.yml) and it works as expected there.

I'm now trying to make a github action that replaces [these lines](https://github.com/pommevilla/friendly-dollop/blob/e3bc1583ec6584e649dca2c110255bfb1b548c30/.github/workflows/quarto-render.yml#L14-L37) that installs the necessary program and renders the documents. The action is [here](https://github.com/pommevilla/quarto-render). When I try to [place the new action in the workflow](https://github.com/pommevilla/quarto-render/blob/main/.github/workflows/test.yml) to render a small testing document, though, some necessary files aren't being copied over and the [resulting page is unstyled](https://pommevilla.github.io/quarto-render/).

The particular files missing from the `gh-pages` branch are:

- `site_libs`
  - `bootstrap`
    - `bootstrap.min.css`, `bootstrap.min.js`
  - `quarto_html/*`
  - `quarto_nav/*`
  - `quarto_search/*`
- `styles.css`

You can see that they're missing in [the `gh-pages` branch of my action](https://github.com/pommevilla/quarto-render/tree/gh-pages), but they are successfully copied over [in a repo that uses a very similar workflow](https://github.com/pommevilla/friendly-dollop/tree/gh-pages). I've put steps in the workflow to list directory contents and I can see the missing files being created [here](https://github.com/pommevilla/quarto-render/actions/runs/969592794) at the various "Check directory" steps. They're just not being copied over for some reason.

I'm not sure why, thoguh, since I'm using pretty much the exact same workflow that has been successful in other repos. I've tried the `keep_files` option but that hasn't changed the results.

### Link to your contents

Repos where workflow has been successfully implemented:

* https://github.com/pommevilla/friendly-dollop
    * [Workflow](https://github.com/pommevilla/friendly-dollop/blob/master/.github/workflows/quarto-render.yml)
    * [Successful run](https://github.com/pommevilla/friendly-dollop/runs/2910329858?check_suite_focus=true)
* https://github.com/NASA-Openscapes/earthdata-cloud-cookbook
    * [Workflow](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/main/.github/workflows/quarto-render.yml)
    * [Successful run](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/runs/2907619375?check_suite_focus=true)

Repo where I'm making my new action based on the above workflows and running into errors:
* https://github.com/pommevilla/quarto-render
    * [Workflow](https://github.com/pommevilla/quarto-render/blob/main/.github/workflows/test.yml)
    * [Action script](https://github.com/pommevilla/quarto-render/blob/main/quarto-install.sh)

### Screenshots

![image](https://user-images.githubusercontent.com/6981612/123343107-b3f35e80-d516-11eb-8f4c-4904af850b69.png)
Files are created during the action workflow

![image](https://user-images.githubusercontent.com/6981612/123341836-47776000-d514-11eb-900b-7b0696c0c654.png)
`gh-page` missing the files

### Additional context

Thank you for any help!

**Comment by peaceiris** [comment]
The root user seems to have ownership of some of the files and directories. Please change the permissions to non-root user (runner).

```
Listing root
total 49888
drwxr-xr-x 7 runner docker     4096 Jun 25 04:49 .
drwxr-xr-x 3 runner docker     4096 Jun 25 04:48 ..
drwxr-xr-x 8 runner docker     4096 Jun 25 04:49 .git
drwxr-xr-x 3 runner docker     4096 Jun 25 04:49 .github
-rw-r--r-- 1 runner docker       17 Jun 25 04:49 .gitignore
drwxr-xr-x 3 root   root       4096 Jun 25 04:49 .quarto
-rw-r--r-- 1 runner docker      396 Jun 25 04:49 Dockerfile
-rw-r--r-- 1 runner docker      588 Jun 25 04:49 README.md
drwxr-xr-x 3 runner docker     4096 Jun 25 04:49 _freeze
-rw-r--r-- 1 runner docker      423 Jun 25 04:49 _quarto.yml
drwxr-xr-x 4 root   root       4096 Jun 25 04:49 _site
-rw-r--r-- 1 runner docker      505 Jun 25 04:49 action.yaml
-rw-r--r-- 1 runner docker      320 Jun 25 04:49 index.qmd
-rw-r--r-- 1 root   root   51022156 Jun 22 22:07 quarto-0.1.292-amd64.deb
-rw-r--r-- 1 runner docker      488 Jun 25 04:49 quarto-install.sh
-rw-r--r-- 1 runner docker       77 Jun 25 04:49 styles.css
Listing site/*:
_site/index_files/:
total 12
drwxr-xr-x 3 root root 4096 Jun 25 04:49 .
drwxr-xr-x 4 root root 4096 Jun 25 04:49 ..
drwxr-xr-x 2 root root 4096 Jun 25 04:49 figure-html

_site/site_libs/:
total 24
drwxr-xr-x 6 root root 4096 Jun 25 04:49 .
drwxr-xr-x 4 root root 4096 Jun 25 04:49 ..
drwxr-xr-x 2 root root 4096 Jun 25 04:49 bootstrap
drwxr-xr-x 2 root root 4096 Jun 25 04:49 quarto-html
drwxr-xr-x 2 root root 4096 Jun 25 04:49 quarto-nav
drwxr-xr-x 2 root root 4096 Jun 25 04:49 quarto-search
Listing site/*:
-rw-r--r-- 1 root root  65604 Jun 25 04:49 _site/site_libs/bootstrap/bootstrap-icons.css
-rw-r--r-- 1 root root 120468 Jun 25 04:49 _site/site_libs/bootstrap/bootstrap-icons.woff
-rw------- 1 root root 174664 Jun 25 04:49 _site/site_libs/bootstrap/bootstrap.min.css
-rw-r--r-- 1 root root  60091 Jun 25 04:49 _site/site_libs/bootstrap/bootstrap.min.js
```

**Comment by pommevilla** [comment]
Nice! I was able to get it to work by adding an additional step to the `test.yml` workflow file [here](https://github.com/pommevilla/quarto-render/blob/3b372ab5276dd275098785f289813e4d6da206bd/.github/workflows/test.yml#L38-L40). This gets all the files copied over correctly and the [site rendering properly](https://pommevilla.github.io/quarto-render/). Thank you!

I have another question about incorporating that line into my action itself because I would like for my users not to have to add an additional `chown -R runner: ./_site` step to their workflow to use this action. I tried to put the `chown` line in the action itself ([commented out here](https://github.com/pommevilla/quarto-render/blob/3b372ab5276dd275098785f289813e4d6da206bd/quarto-install.sh#L27)), but I got an error saying that `runner:` was an invalid spec. I printed out the users during the `quarto-install.sh` script and here's the list of the users at that step:
![image](https://user-images.githubusercontent.com/6981612/123430260-97ded400-d58d-11eb-84d2-5ed9829b2276.png)

and here's what we see when we run it as part of the main workflow:
![image](https://user-images.githubusercontent.com/6981612/123430542-edb37c00-d58d-11eb-9a34-c6a0e76a6800.png)

I'm guessing it has something to do with the fact that the action is running in its own Docker container. Do you have any ideas how to add the `chmod` line into my action so users don't have to add it into their own workflow? I tried googling around but I couldn't find anything useful.

**Comment by pommevilla** [comment]
Nevermind, I figured it out. I didn't need to run the workflow from a Docker container. I converted the action to a composite action and everything's working now. Thank you so much for your help! Closing.
