### ISSUE TITLE
support: meet the problem when loading the ssh key

### ISSUE THREAD

**Issue by giantpetter** [peaceiris/actions-gh-pages#635]
### Checklist

- [X] I am using the latest version of this aciton.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe the bug

 I have try numbers of times but in vain, these errors always occur. could you please tell me how to fix it? thanks
 ```
Error loading key "/home/runner/.ssh/github": invalid format
  Error: Action failed with "The process '/usr/bin/ssh-add' failed with exit code 1"
```

### Relevant links

```markdown
Public repository:https://github.com/giantpetter/giantpetter.github.io.source/runs/3211517353
YAML config:https://github.com/giantpetter/giantpetter.github.io.source/blob/master/.github/workflows/public.yml
YAML workflow:
```

### Relevant log output

```
Run peaceiris/actions-gh-pages@v3
[INFO] Usage https://github.com/peaceiris/actions-gh-pages#readme
Dump inputs
Setup auth token
  [INFO] setup SSH deploy key
  /usr/bin/chmod 700 /home/runner/.ssh
  [INFO] wrote /home/runner/.ssh/known_hosts
  /usr/bin/chmod 600 /home/runner/.ssh/known_hosts
  [INFO] wrote /home/runner/.ssh/github
  /usr/bin/chmod 600 /home/runner/.ssh/github
  [INFO] wrote /home/runner/.ssh/config
  /usr/bin/chmod 600 /home/runner/.ssh/config
  /usr/bin/ssh-add /home/runner/.ssh/github
  Error loading key "/home/runner/.ssh/github": invalid format
  Error: Action failed with "The process '/usr/bin/ssh-add' failed with exit code 1"
```

### Additional context.

https://github.com/giantpetter/giantpetter.github.io/runs/3211851861?check_suite_focus=true

**Comment by peaceiris** [comment]
Please follow the [Create SSH Deploy Key](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-ssh-deploy-key) section.

**Comment by peaceiris** [comment]
Also see the [Deploy to external repository `external_repository`](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-external-repository-external_repository) section.

> When you use `deploy_key`, set your private key to the repository which includes this action and set your public key to your external repository.

**Comment by giantpetter** [comment]
ok, thanks.
