### ISSUE TITLE
support: gh-pages not seeing the static files, nothing to comit, no changes published to GHP

### ISSUE THREAD

**Issue by lukaszbudnik** [peaceiris/actions-gh-pages#644]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

I've been successfully using this action already. I haven't made any changes to my project since May which is when I had the last successful deploy.

Yesterday I merged some pull requests but noticed that my build no longer is published and gh-pages action is saying that there is nothing to commit.

I have 2 phase Build and Deploy pipeline. Build is publishing artifacts and Deploy is downloading them.

I'm getting this error:

```
  [INFO] copy /home/runner/work/hotel-spa/hotel-spa/build to /home/runner/actions_github_pages_1629273702012
  cp: no such file or directory: /home/runner/work/hotel-spa/hotel-spa/build/.*
```

And later I see:
```
Create a commit
  /usr/bin/git commit -m deploy: 4e20060e622145b1d0535a16632dc821158b9e40
  On branch gh-pages
  nothing to commit, working tree clean
  [INFO] skip commit
Push the commit or tag
  /usr/bin/git push origin gh-pages
  Everything up-to-date
```

I've even added additional changes to build file to include:
```
      - run: pwd
      - run: ls -l
      - run: ls -l build
 ```

and I see that the build files are correctly fetched from artifacts. However, gh-pages is not seeing them.

Link to my build: https://github.com/lukaszbudnik/hotel-spa/runs/3358806106?check_suite_focus=true

My build definition: https://github.com/lukaszbudnik/hotel-spa/blob/main/.github/workflows/deploy-ghp.yml

Any hints would be most welcomed.

### Relevant links

```markdown
Public repository: https://github.com/lukaszbudnik/hotel-spa/
YAML config: https://github.com/lukaszbudnik/hotel-spa/blob/main/.github/workflows/deploy-ghp.yml
YAML workflow: https://github.com/lukaszbudnik/hotel-spa/blob/main/.github/workflows/deploy-ghp.yml
```

### Relevant log output

```
(...)
  [INFO] copy /home/runner/work/hotel-spa/hotel-spa/build to /home/runner/actions_github_pages_1629273702012
  cp: no such file or directory: /home/runner/work/hotel-spa/hotel-spa/build/.*
(...)
Create a commit
  /usr/bin/git commit -m deploy: 4e20060e622145b1d0535a16632dc821158b9e40
  On branch gh-pages
  nothing to commit, working tree clean
  [INFO] skip commit
Push the commit or tag
  /usr/bin/git push origin gh-pages
  Everything up-to-date
```

### Additional context.

The last successful deploy was back in May (I haven't merged any pull requests since then - except yesterday when I saw the issue): https://github.com/lukaszbudnik/hotel-spa/deployments/activity_log?environment=github-pages

**Comment by peaceiris** [comment]
> nothing to commit, working tree clean

It means that you have changed some source codes but build assets have not changed.

**Comment by lukaszbudnik** [comment]
hm... you are right I didn't change the application logic, I was merging dependabot pull requests (with new dependencies versions). I have to analyse how yarn build is generating the production files.
Thanks for the pointer.

**Comment by peaceiris** [comment]
The log message will be improved in the next major version. Please ask me if you have another question ;-)
