### ISSUE TITLE
support: Error: Action failed with "not found deploy key or tokens"

### ISSUE THREAD

**Issue by maifeeulasad** [peaceiris/actions-gh-pages#651]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

I'm getting started with react CI/CD. 

So I created a key, and put them in my repo, like this: 
![Screenshot from 2021-09-06 18-04-30](https://user-images.githubusercontent.com/29339330/132215113-d7137b90-cd58-4503-bf3f-994cc201d16a.png)

And pushed after that, but as you can see, the deployment is failing: https://github.com/maifeeulasad/react-pipeline/runs/3524377241?check_suite_focus=true

I've seen this answer: https://github.com/peaceiris/actions-gh-pages/issues/123#issuecomment-589958345

And I'm using what is being told to use. But still, it's giving me this error:
```
Error: Action failed with "not found deploy key or tokens"
```

### Relevant links

```markdown
Public repository:https://github.com/maifeeulasad/react-pipeline
YAML config:
YAML workflow:https://github.com/maifeeulasad/react-pipeline/blob/main/.github/workflows/pipeline.yml
```

### Relevant log output

```
Run peaceiris/actions-gh-pages@v3
  with:
    publish_dir: ./build
    publish_branch: gh-pages
    allow_empty_commit: false
    keep_files: false
    force_orphan: false
    enable_jekyll: false
    disable_nojekyll: false
    exclude_assets: .github
[INFO] Usage https://github.com/peaceiris/actions-gh-pages#readme
Dump inputs
  [INFO] : true
  [INFO] PublishBranch: gh-pages
  [INFO] PublishDir: ./build
  [INFO] DestinationDir: 
  [INFO] ExternalRepository: 
  [INFO] AllowEmptyCommit: false
  [INFO] KeepFiles: false
  [INFO] ForceOrphan: false
  [INFO] UserName: 
  [INFO] UserEmail: 
  [INFO] CommitMessage: 
  [INFO] FullCommitMessage: 
  [INFO] TagName: 
  [INFO] TagMessage: 
  [INFO] EnableJekyll (DisableNoJekyll): false
  [INFO] CNAME: 
  [INFO] ExcludeAssets .github
  
Setup auth token
  Error: Action failed with "not found deploy key or tokens"
```

### Additional context.

It has even write access.

**Comment by peaceiris** [comment]
https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-ssh-deploy-key

> - Go to *Deploy Keys* and add your *public* key with the *Allow write access*
> - Go to *Secrets* and add your *private* key as `ACTIONS_DEPLOY_KEY`

Did you add your private key?

**Comment by maifeeulasad** [comment]
I somehow mixed two different keys. Thanks a lot.
