### ISSUE TITLE
proposal: Bump node from 12 to 16

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-gh-pages#677]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your proposal

Bump runtime version from `node12` to `node16`

### Describe the solution you'd like

- update `action.yml`
- update test
- update CI

### Describe alternatives you've considered

N/A

### Additional context

- https://github.com/actions/runner/issues/772
- https://github.com/actions/runner/pull/1439

**Comment by yashash1511** [comment]
node18 was released today.

**Comment by Mo3et** [comment]
I want to know when to bump the node from 12 to 16 for the release version.

**Comment by peaceiris** [comment]
I am planning the next major release from node12 to node16 this weekend.

**Comment by peaceiris** [comment]
https://github.com/peaceiris/actions-gh-pages/releases/tag/v3.9.0
