### ISSUE TITLE
support: Error deploying to the external repository

### ISSUE THREAD

**Issue by dudarboh** [peaceiris/actions-gh-pages#682]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

Hi,

I am trying to deploy doxygen documentation generated in repository A to my github pages repository B.

I have tried to follow the instructions provided in the README, which are:
- generate pair of private/public rsa keys
- add private key to the repository A (the one with Actions) to the `secrets` with a name `ACTIONS_DEPLOY_KEY` 
- add public key to the deploy keys of repository B (pages)
- add the action step as:
```
            - name: Deploy website
              uses: peaceiris/actions-gh-pages@v3
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  external_repository: dudarboh/dudarboh.github.io
                  publish_branch: gh-pages
                  publish_dir: ./doc/doxygen_api/html
```

and I stumble on the error:
`Error: Action failed with "The process '/usr/bin/ssh-add' failed with exit code 1"`

Could you give me a hint if I am doing something wrong?

cheers

### Relevant links

```markdown
Public repository: https://github.com/dudarboh/LCIO/tree/test-doc
External repository for website: https://github.com/dudarboh/dudarboh.github.io
YAML config: https://github.com/dudarboh/LCIO/blob/test-doc/.github/workflows/docs.yml
YAML workflow: https://github.com/dudarboh/LCIO/runs/4563029468?check_suite_focus=true
```

### Relevant log output

```
Run peaceiris/actions-gh-pages@v3
[INFO] Usage https://github.com/peaceiris/actions-gh-pages#readme
Dump inputs
Setup auth token
  [INFO] setup SSH deploy key
  /usr/bin/chmod 700 /home/runner/.ssh
  [INFO] wrote /home/runner/.ssh/known_hosts
  /usr/bin/chmod 600 /home/runner/.ssh/known_hosts
  [INFO] wrote /home/runner/.ssh/github
  /usr/bin/chmod 600 /home/runner/.ssh/github
  [INFO] wrote /home/runner/.ssh/config
  /usr/bin/chmod 600 /home/runner/.ssh/config
  /usr/bin/ssh-add /home/runner/.ssh/github
  Error loading key "/home/runner/.ssh/github": invalid format
  Error: Action failed with "The process '/usr/bin/ssh-add' failed with exit code 1"
```

### Additional context.

Maybe you will have any immediate idea what could cause this?

Thank you!

**Comment by peaceiris** [comment]
Did you use the following command to generate a pair of public/private keys?

```console
$ ssh-keygen -t rsa -b 4096 -C "$(git config user.email)" -f gh-pages -N ""
# You will get 2 files:
#   gh-pages.pub (public key)
#   gh-pages     (private key)
```

**Comment by dudarboh** [comment]
yes

**Comment by peaceiris** [comment]
It is really worth trying to generate a pair of public/private keys, check which is *public/private* key, and register the keys again.

**Comment by dudarboh** [comment]
It works.

Copying private key's `-----BEGIN RSA PRIVATE KEY-----` and `-----END RSA PRIVATE KEY-----` lines seems important...

Sorry for this newbie issue :)

cheers
