### ISSUE TITLE
support: Rename the workflow name from pages-build-deployment to something else

### ISSUE THREAD

**Issue by ma-sadeghi** [peaceiris/actions-gh-pages#707]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

Currently, this Action triggers another Action which is named "pages-build-deployment". Is there an option to rename it to something else?

### Relevant links

```markdown
Not applicable
```

**Comment by peaceiris** [comment]
See this comment: https://github.com/peaceiris/actions-gh-pages/discussions/688#discussioncomment-1867466

To put it simply, that job is not under our control.

**Comment by ma-sadeghi** [comment]
Thank you for the detailed explanation!
