### ISSUE TITLE
support: 

### ISSUE THREAD

**Issue by kevinehosford** [peaceiris/actions-gh-pages#710]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

Why is the `.github` dir in the repository deleted?

### Relevant links

Step:

```markdown
- name: Deploy pages
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ env.PRIVATE_MODULE_TOKEN }}
          publish_branch: main
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          publish_dir: .
```

### Relevant log output

Output from the run showing workflow file being removed:

```
  /usr/bin/git rm -r --ignore-unmatch *
  rm '.github/workflows/jobs.yaml'
```

**Comment by peaceiris** [comment]
Please read this section on the README.md: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-filter-publishing-assets-exclude_assets

**Comment by kevinehosford** [comment]
That was what I needed, thanks!
