### ISSUE TITLE
support: folder name dist is ignored

### ISSUE THREAD

**Issue by mimidotsuser** [peaceiris/actions-gh-pages#711]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

Following is my workflow snippet before upload

![Screenshot from 2022-02-16 21-10-47](https://user-images.githubusercontent.com/25152892/154329015-48a0202a-00a7-44c4-a157-9b1f1375b2c8.png)

and the logs
![Screenshot from 2022-02-16 21-09-24](https://user-images.githubusercontent.com/25152892/154329075-912a7078-01d4-4799-a8ed-5b68418deda6.png)

But the `dist` folder is never published

### Relevant links

```markdown
Public repository: https://github.com/mimidotsuser/h5p-standalone-examples
YAML config:https://github.com/mimidotsuser/h5p-standalone-examples/blob/e01cfb1f681df76acc02d2797bc3f41f92d59268/.github/workflows/deploy.yml
YAML workflow: https://github.com/mimidotsuser/h5p-standalone-examples/actions/runs/1854437240
```

**Comment by peaceiris** [comment]
```diff
- publish_dir: .
+ publish_dir: dist
```

**Comment by peaceiris** [comment]
Just your `.gitignore` has `dist`.

**Comment by mimidotsuser** [comment]
thank you @peaceiris. That make sense now since the deployment uses `git`. 
I have opted to deleting the .gitignore before calling the action. It would be awesome if this caveat was included in the docs. 
Thank you.

**Comment by peaceiris** [comment]
This action does not recommend that approach (`publish_dir: .`). There are some things to worry about like workflow files under the `.github` folder, the `.gitignore` file, and so on. Users sometimes forget those. We should understand what we want to deploy. To make your settings simple, I recommend creating a directory like public or dist for your deployment and passing it to the publish_dir. Thank you.
