### ISSUE TITLE
support: execution from hashref disabled/broken vs GitHub Actions Security Best Practice?

### ISSUE THREAD

**Issue by HariSekhon** [peaceiris/actions-gh-pages#712]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

Why is execution from the main branch latest hashref disabled/broken when this is the GitHub Actions Security Best Practice to pin 3rd party github actions to an immutable hashref?

I've already seen issues #84 and #98 but there wasn't any reason given in those tickets other than using v2 / v3 tags, but this contradicts GitHub's own security recommendations to not use tags for 3rd parties, see this doc section:

https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

Is it intentional to break execution from main branch hashref or is this a mistake, and if intentional, why?

Update: I had assumed that the latest main hashref would contain the fixes in v3, but for now I'll try using `peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305` which is the v3 tag's current hashref for immutability.

### Relevant links

```markdown
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
```

**Comment by peaceiris** [comment]
That's odd. It works well for us.

https://github.com/peaceiris/test-mdbook/commit/99dd8fa5b5d63b8591a2626727e4b6bb685f0227

**Comment by peaceiris** [comment]
> Update: I had assumed that the latest main hashref would contain the fixes in v3, but for now I'll try using peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 which is the v3 tag's current hashref for immutability.

I have left a comment on an issue somewhere in the past, but I couldn't find it, so I'll restate it here. Our project builds and provides build assets only when creating a release. This is to prevent the user from executing this action with the main branch. For example, if we maintain build assets in the main branch and users use this action as follows, a major release including breaking changes will break the CI workflow of the users silently.

https://github.com/peaceiris/actions-gh-pages/blob/c921422e3791023a8dd39566a129863ff42e8c39/release.sh#L52-L61
