### ISSUE TITLE
support: deploy key doesn't work

### ISSUE THREAD

**Issue by AaronErhardt** [peaceiris/actions-gh-pages#719]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

Do deploy keys work in a GitHub organization?

I've tried using deploy keys and followed [these steps](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-ssh-deploy-key), yet I couldn't get the workflow running.

And if I use the same command to clone the repository on my local machine, it works for some reason.

```
git clone --depth=1 --single-branch --branch gh-pages git@github.com:Relm4/website.git
```

I have used the exact same private key that I've uploaded as secret for the workflow run.

My current knowledge of this issue is the following:
1. Deploy key authentication works on my local machine
2. It doesn't work in the workflow with the same key.

I've set my private key as `ACTIONS_DEPLOY_KEY` to
```
-----BEGIN OPENSSH PRIVATE KEY-----
ACTUAL_KEY_VALUE....
-----END OPENSSH PRIVATE KEY-----
```

Thanks for your work on this! Everything has worked perfectly so far, except for this exception.

### Relevant links

+ Public repository: [https://github.com/Relm4/docs](https://github.com/Relm4/docs)
+ YAML workflow: [https://github.com/Relm4/docs/actions/runs/1980049011/workflow](https://github.com/Relm4/docs/actions/runs/1980049011/workflow)

### Relevant log output

Setup auth token
  [INFO] setup SSH deploy key
  /usr/bin/chmod 700 /github/home/.ssh
  [INFO] wrote /github/home/.ssh/known_hosts
  /usr/bin/chmod 600 /github/home/.ssh/known_hosts
  [INFO] wrote /github/home/.ssh/github
  /usr/bin/chmod 600 /github/home/.ssh/github
  [INFO] wrote /github/home/.ssh/config
  /usr/bin/chmod 600 /github/home/.ssh/config
  /usr/bin/ssh-add /github/home/.ssh/github
  Identity added: /github/home/.ssh/github (aaron.erhardt@t-online.de)

Prepare publishing assets
  [INFO] ForceOrphan: false
  /usr/bin/git clone --depth=1 --single-branch --branch gh-pages git@github.com:Relm4/website.git /github/home/actions_github_pages_1647254957429
  Cloning into '/github/home/actions_github_pages_1647254957429'...
  Host key verification failed.
  fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.

**Comment by AaronErhardt** [comment]
This seems to be rather an issue with the fedora based container I'm using. After days of investigation I'm still not able to find the cause... But it doesn't seem to be related to this project.

**Comment by AaronErhardt** [comment]
For reference, this was my solution: https://github.com/Relm4/docs/blob/main/fix_ssh.sh
I can't believe how many hours it took me to figure out this solution...

**Comment by peaceiris** [comment]
Thank you for investigating and sharing the solution!

> ```sh
> #!/bin/bash
> 
> # Return on error
> set -e
> 
> # Overwrite global SSH configuration
> echo "Host *
>   StrictHostKeyChecking no
>   UserKnownHostsFile=/dev/null
> " > /etc/ssh/ssh_config
> ```

I will consider this case in #686
