### ISSUE TITLE
proposal: Allow option to mirror current commit message on external repo commit message

### ISSUE THREAD

**Issue by fabiosangregorio** [peaceiris/actions-gh-pages#72]
When using `EXTERNAL_REPOSITORY`, the only option for the commit message is currently
```
COMMIT_MESSAGE="Automated deployment: $(date -u) ${GITHUB_SHA}"
```
It would be awesome if we could have the option to have the message of the commit we're currently deploying as the commit message for the external repo, in order to see on the external repo what we've just deployed, instead of the current generic message.

**Comment by peaceiris** [comment]
Go to #73
