### ISSUE TITLE
support: 

### ISSUE THREAD

**Issue by stardustman** [peaceiris/actions-gh-pages#724]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

how to use this actions in a repo such as named `blog` to deploy the static web pages directly to `https://<user>.github.io/`, not the `blog` repo?

### Relevant links

```markdown
Public repository: https://github.com/stardustman/blog
YAML config:
YAML workflow: https://github.com/stardustman/blog/.github/workflows/deploy.yml
```

### Relevant log output

https://github.com/stardustman/blog/actions/runs/2008535885
the actions log at here.

**Comment by peaceiris** [comment]
https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-external-repository-external_repository

**Comment by stardustman** [comment]
Thanks
