### ISSUE TITLE
deploy denied due to lack of permissions

### ISSUE THREAD

**Issue by HunteRoi** [peaceiris/actions-gh-pages#725]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

My action fails when trying to deploy the build to **gh-pages** branch.
The error is: `Branch "gh-pages" is not allowed to deploy to github-pages due to environment protection rules.`

I have tried to switch to deploy_key without success. I have not changed the workflow since the last use (which processed successfully by the way).

### Relevant links

```markdown
Public repository: https://github.com/Section-IG/wiki
YAML workflow: https://github.com/Section-IG/wiki/blob/main/.github/workflows/deploy.yml
Action: https://github.com/Section-IG/wiki/actions/runs/2031429188
```

### Relevant log output

/

### Additional context.

/

**Comment by HunteRoi** [comment]
Not sure but might be related to this: 
![image](https://user-images.githubusercontent.com/32441291/159816740-4cac173d-04f9-48b4-a513-ad8ddc8d7d0f.png)

**Comment by peaceiris** [comment]
Why don't you allow the `gh-pages` branch, not the `main` branch? ;)

---

My test run with allowing `main` branch only: https://github.com/peaceiris/hugo-theme-iris/actions/runs/2034333371

![スクリーンショット 2022-03-24 21 44 05](https://user-images.githubusercontent.com/30958501/159918857-ac38320f-c89b-4f4b-a479-45c5e32c490a.png)

The error message just says:

> Branch "gh-pages" is not allowed to deploy to github-pages due to environment protection rules.

**Comment by HunteRoi** [comment]
Thank you for the hint! Have a nice day :D
