### ISSUE TITLE
proposal: Custom commit message option

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-gh-pages#74]
**Is your feature request related to a problem? Please describe.**

cf. #72 and #73 by @fabiosangregorio

**Describe the solution you'd like**

```yaml
with:
  commitMessage: ${{ github.event.commits[0].message }}
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by peaceiris** [comment]
How about this approach? @fabiosangregorio

**Comment by fabiosangregorio** [comment]
@peaceiris this would be perfect!
