### ISSUE TITLE
support: Can't deploy a Hugo site due to "The requested URL returned error: 403"

### ISSUE THREAD

**Issue by EmilySeville7cfg** [peaceiris/actions-gh-pages#744]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

I have a [personal repo](https://github.com/EmilySeville7cfg/EmilySeville7cfg.github.io) and I want deploy this site. But I can't due to [`The requested URL returned error: 403`](https://github.com/EmilySeville7cfg/EmilySeville7cfg.github.io/runs/6324319546?check_suite_focus=true#step:5:106) error. Why it happens? What am I missing to successfully deploy my site? As I understand:

- site is being built to `public` folder
- this folder contents is pushed to `gh-pages`
- `gh-pages` is used to deploy site

Is it right? Why there is no `gh-pages` branch created after any new commit?

### Relevant links

```markdown
Public repository: https://github.com/EmilySeville7cfg/EmilySeville7cfg.github.io
YAML config: https://github.com/EmilySeville7cfg/EmilySeville7cfg.github.io/blob/master/config.yml
YAML workflow: https://github.com/EmilySeville7cfg/EmilySeville7cfg.github.io/blob/master/.github/workflows/cd.yml
```

### Relevant log output

https://github.com/EmilySeville7cfg/EmilySeville7cfg.github.io/runs/6324319546?check_suite_focus=true#step:5:106

**Comment by peaceiris** [comment]
This is the same as the issue https://github.com/peaceiris/actions-gh-pages/issues/742#issuecomment-1114440714

Please change the repository setting (Go to `Actions` > `General` > `Workflow permissions`) as follows:

![スクリーンショット 2022-05-06 23 26 07](https://user-images.githubusercontent.com/30958501/167153241-dde81752-457c-4061-91f8-49edc0222be8.png)

**Comment by EmilySeville7cfg** [comment]
Hm... Issue is solved but my [site](https://emilyseville7cfg.github.io/) is still inaccessible. 🤔

**Comment by peaceiris** [comment]
We need to select the branch to deploy in the Pages tab of the repository settings.

![スクリーンショット 2022-05-06 23 36 46](https://user-images.githubusercontent.com/30958501/167155025-c8748d10-c184-41b9-b11a-c59675fe9e6a.png)

**Comment by EmilySeville7cfg** [comment]
`Your GitHub Pages site is currently being built from the master branch` is confusing description because when I hear `built` I think about just building site via some static site generator.

**Comment by yashash1511** [comment]
> We need to select the branch to deploy in the Pages tab of the repository settings.
> 
> ![スクリーンショット 2022-05-06 23 36 46](https://user-images.githubusercontent.com/30958501/167155025-c8748d10-c184-41b9-b11a-c59675fe9e6a.png)

would be nic if a notice about this is added to the documentation

**Comment by yashash1511** [comment]
> Please change the repository setting (Go to `Actions` > `General` > `Workflow permissions`) as follows:
> 
> * Toggle the `Read and write permissions`

would be nic if a notice about this is added to the documentation

**Comment by peaceiris** [comment]
#753 is another solution.
