### ISSUE TITLE
support: how to specify root directory for external_repository

### ISSUE THREAD

**Issue by acgetchell** [peaceiris/actions-gh-pages#755]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

I have the source of my blog here:

https://github.com/acgetchell/blog

Which is configured to publish to my repo here:

https://github.com/acgetchell/acgetchell.github.io

At the root directory of the master branch.

I've specified `publish_dir: ./`, however when this action runs it still generates everything in the public directory (as well as overwriting the root directory).

I've been `git push -f` from a local copy of acgetchell.github.io to revert.

### Relevant links

```markdown
Public repository: https://github.com/acgetchell/blog

YAML config: https://github.com/acgetchell/blog/blob/35d91bb13b773f90b8745d49bca901f55e4bb5df/config.toml

YAML workflow: https://github.com/acgetchell/blog/blob/35d91bb13b773f90b8745d49bca901f55e4bb5df/.github/workflows/main.yml
```

### Additional context.

Everything ends up on www.adamgetchell.org/public/ except broken.

**Comment by peaceiris** [comment]
You can refer to [the Hugo example workflow](https://github.com/peaceiris/actions-gh-pages#getting-started). It has `publish_dir: ./public`.

**Comment by acgetchell** [comment]
Thanks, I figured it out. `publish_dir:` is the *source* of what the action pushes to the remote repo, not the destination.
