### ISSUE TITLE
support: Follow-up "pages build and deployment" triggered by gh-pages not happening

### ISSUE THREAD

**Issue by anchal-physics** [peaceiris/actions-gh-pages#780]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

I used peaceiris/actions-gh-pages@v3 in one of my other [repositories](https://github.com/anchal-physics/personalWebpage) with exact same workflow file. There, after the "deploy" job, a new job named "pages build and deployment" is always deployed automatically which I believe deploys website from gh-pages branch to the github.io url.
However, in the repo named 'site' linked below here, the same workflow does not do the same. The "deploy" job works as expected and gh-pages branch is successfully updated by it. But the follow-up job is not triggered in this repository. I've tried to find out any difference between the two repository, but couldn't find any. Could you help with this issue please? Thanks.

### Relevant links

```markdown
Public repository: https://github.com/anchal-physics/site
YAML config: https://github.com/anchal-physics/site/blob/main/_config.yml
YAML workflow: https://github.com/anchal-physics/site/blob/main/.github/workflows/deploy.yml
```

**Comment by peaceiris** [comment]
https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token

**Comment by anchal-physics** [comment]
Thanks, that solves it.
