### ISSUE TITLE
proposal: Upgrade NodeJS

### ISSUE THREAD

**Issue by ofek** [peaceiris/actions-gh-pages#788]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your proposal

Actions says:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: peaceiris/actions-gh-pages
```

### Describe the solution you'd like

Upgrade NodeJS

**Comment by peaceiris** [comment]
Thanks, duplicate of https://github.com/peaceiris/actions-gh-pages/issues/677

**Comment by ofek** [comment]
Ah, thank you!

**Comment by peaceiris** [comment]
https://github.com/peaceiris/actions-gh-pages/releases/tag/v3.9.0
