### ISSUE TITLE
Update mkdocs example

### ISSUE THREAD

**Issue by tupaschoal** [peaceiris/actions-gh-pages#8]
If I understood correctly, the `mkdocs` example uses the retired `actions-pipenv`. It this statement holds, it might be worth updateing the example to a supported architecture

**Comment by peaceiris** [comment]
Yes, I will update.

**Comment by tupaschoal** [comment]
Thanks! I'm just discovering the GitHub actions and was unsure if I had misunderstood

**Comment by tupaschoal** [comment]
Thank you, I'll test as soon as I can and provide feedback, if any!
