### ISSUE TITLE
support: 

### ISSUE THREAD

**Issue by joemcglinchy** [peaceiris/actions-gh-pages#801]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

I am seeing the code cells of my `.ipynb` files rendered without formatting. I'm not exactly sure where to place this issue, I have it in jupyter-book too but haven't gotten any movement yet. If this is the incorrect venue for this issue, please let me know and i will close.

https://github.com/executablebooks/jupyter-book/issues/1896

### Relevant links

```markdown
Public page: https://hydrosat.github.io/fusion-hub-docs/examples/order-service-example.html
Public repository: repo is private
YAML config: repo is private
YAML workflow: repo is private
```

**Comment by dhimmel** [comment]
I don't think this issue has any relation to this repo. This repo is an GitHub action to deploy to branches. It's not related to jupyter notebooks. Also the title of the issue is non-descript.

I'd suggest closing or even deleting.

**Comment by joemcglinchy** [comment]
thanks, I was covering my bases by cross-posting. turns out it was an ipython issue with executable books https://github.com/executablebooks/jupyter-book/issues/1896
