### ISSUE TITLE
support: The URL of the GitHub pages changes on its own

### ISSUE THREAD

**Issue by yuta-hidaka** [peaceiris/actions-gh-pages#846]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

When I deploy a private static website in a private repository using GithubAction, the URL sometimes changes.

Is this a specification of this GitHubActions? (Or is it a GitHub Pages specification?) .

I would like to know why the URL sometimes changes and how to prevent the URL from changing.

### Relevant links

```markdown
Public repository:
YAML config:
YAML workflow:
```

**Comment by peaceiris** [comment]
It looks like a feature of the GitHub Enterprise Cloud. (called `Privately published sites` and deployed to `https://*.pages.github.io` path patterns)

https://docs.github.com/en/enterprise-cloud@latest/pages/getting-started-with-github-pages/changing-the-visibility-of-your-github-pages-site

We can configure a custom domain to access a constant domain pattern.

https://docs.github.com/en/enterprise-cloud@latest/pages/configuring-a-custom-domain-for-your-github-pages-site

**Comment by yuta-hidaka** [comment]
@peaceiris 

Hi!
Does that mean we have no control over the part of * of https://*.pages.github.io?

> We can configure a custom domain to access a constant domain pattern.
According to this article.
We should use CNAME for DNS, meaning we need the URL that never changed. So it might be still a problem🤔

Should I post it on [actions/deploy-pages@v1](https://github.com/actions/deploy-pages) GitHub issue?

**Comment by peaceiris** [comment]
> Does that mean we have no control over the part of * of https://*.pages.github.io?

yes.

> We should use CNAME for DNS (If we use a subdomain), meaning we need the URL that never changed. So it might be still a problem

It is a specification of the GitHub Pages on the GitHub Enterprise Cloud. Currently, we have no way to deploy our site to an URL that never will be changed on a private Enterprise Cloud repository except to configure a custom domain. (I am also using the GitHub Pages on the GitHub Enterprise Cloud and configuring a custom domain to access an URL that never will be changed.)

If we have our custom domain, the GitHub Pages support CNAME files so we can put a CNAME file or set our domain as follows with this action.

https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-add-cname-file-cname

> Should I post it on actions/deploy-pages GitHub issues?

- https://github.com/community/community/discussions/21581
- https://github.com/community/community/discussions/30373

The above previous discussions may help you. And we can request new features to GitHub at [community/community](https://github.com/community/community). Of course, the actions/deploy-pages repository is also a good place to ask about that, I think.

**Comment by peaceiris** [comment]
- https://github.com/orgs/community/discussions/21581

According to the thread, actually, we can access a static URL `https://<ORG_NAME>.github.io/<REPO_NAME>` and it redirects to an internal URL like `https://hoge-fuga-abc1234.pages.github.io/`

**Comment by yuta-hidaka** [comment]
@peaceiris 

Thank you so much!

I tried this https://<ORG_NAME>.github.io/<REPO_NAME> then it worked.

But changing the URL is not cool...

I gonna post about URLs on the GitHub community.

Again thank you so much.
あまり関係のない内容だったのに丁寧に教えていただき、ありがとうございました🙇
