### ISSUE TITLE
proposal: update documentation to give write permission to workflows

### ISSUE THREAD

**Issue by yakimant** [peaceiris/actions-gh-pages#852]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your proposal

Currently, using the default documentation will fail the action. This issue is described here:
https://github.com/peaceiris/actions-gh-pages/issues/742

### Describe the solution you'd like

I sugggest to add requirement for Write to repo documentation and official document:
https://gohugo.io/hosting-and-deployment/hosting-on-github/

**Comment by peaceiris** [comment]
I totally agree with you. I will update it. ʕ◔ϖ◔ʔ

**Comment by peaceiris** [comment]
- fixed by https://github.com/gohugoio/hugoDocs/pull/1991
