### ISSUE TITLE
Bug: fails if the gh-pages branch doesn't exist

### ISSUE THREAD

**Issue by noc7c9** [peaceiris/actions-gh-pages#91]
**Describe the bug**
I've attempted to use this action in a new repository where the branch doesn't exist.

I found [this issue](https://github.com/peaceiris/actions-gh-pages/issues/31) but it recommends using `ACTIONS_DEPLOY_KEY` which I am and setting `emptyCommits: true` which isn't the behaviour I want.

I managed to solve this by creating the gh-pages branch and rerunning the workflow but I feel like this action would be much friendlier but not having this issue in the first place.

**To Reproduce**
1. Create a new repository with an index.html file on the master branch
2. Setup workflow config as above
3. Trigger workflow
4. Workflow fails with
```
/usr/bin/git clone --depth=1 --single-branch --branch gh-pages git@github.com:noc7c9/i-love-hue-rs-clone.git /home/runner/actions_github_pages
Cloning into '/home/runner/actions_github_pages'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
warning: Could not find remote branch gh-pages to clone.
fatal: Remote branch gh-pages not found in upstream origin
##[error]Action failed with "Error: Error: The process '/usr/bin/git' failed with exit code 128"
##[error]Node run failed with exit code 1
```
**Expected behavior**
I expected the action to create the branch since it doesn't exist.

**Your YAML file**
https://github.com/noc7c9/i-love-hue-rs-clone/blob/master/.github/workflows/gh-pages.yml

Relevant part of the file:
```yml
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  publish_dir: ./target/deploy
```

**Comment by peaceiris** [comment]
@noc7c9 
Thank you for reporting.

This problem was fixed by #92 

The v3.0.3 has been released and the v3 tag updated. Try to use v3!

**Comment by peaceiris** [comment]
And all options were renamed on v3. Check [actions-gh-pages/action.yml at v3](https://github.com/peaceiris/actions-gh-pages/blob/v3/action.yml)

**Comment by noc7c9** [comment]
Hey thanks for the quick fix (and the project too!). It's working perfectly now.
