### ISSUE TITLE
support: The depoly step is skipped and gh-pages doesn't generated

### ISSUE THREAD

**Issue by quanshengwu** [peaceiris/actions-gh-pages#924]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

Dear Sir/Madame, 

Thanks for developing such wonderful tools. 

I am using it together with Sphinx to generate gh-pages for my code. Now I meet the following problem. 
![image](https://github.com/peaceiris/actions-gh-pages/assets/10760633/b80932bd-7d74-4c3d-9d60-15d44ef01aaa)
**Everything works fine except the Deploy step is skipped and the gh-pages branch doesn't generate.** 

Firstly, as a test, I followed the steps in https://coderefinery.github.io/documentation/gh_workflow/ and build a test-sphinx code (https://github.com/quanshengwu/test-sphinx). Everything works fine. The gh-pages branch was generated successfully. 

Then I use modified the workflow a little bit to fit my repository, it just doesn't generate the right gh-pages branch. 

Any help would be appreciated.

Best regards, 
QuanSheng Wu

### Relevant links

```markdown
Public repository:https://github.com/quanshengwu/wannier_tools
YAML config:
YAML workflow: https://github.com/quanshengwu/wannier_tools/blob/master/.github/workflows/sphinx.yaml
```

### Relevant log output

<img width="458" alt="image" src="https://github.com/peaceiris/actions-gh-pages/assets/10760633/eca4a2f2-4df8-42ab-ab30-8bdff89296bd">

https://github.com/quanshengwu/wannier_tools/actions/runs/5281530268/jobs/9555239351

**Comment by peaceiris** [comment]
Please check this filter.

```diff
- if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
+ if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
```

**Comment by quanshengwu** [comment]
@peaceiris 
Thank you so so much for you quick reply. It works just great!
