### ISSUE TITLE
support: Github Pages not deployed, even when action is successfull

### ISSUE THREAD

**Issue by anticdimi** [peaceiris/actions-gh-pages#961]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

Hi @peaceiris ,
Thank you for your work, it really is useful!

My website can't deploy correctly. It seems like the `public/`dir is not created in the correct location (see the log output bellow).
Any hints on how to solve this?

### Relevant links

```markdown
Public repository: /
YAML config: 

name: Deploy GitHub Pages

on:
  push:
    branches:
      - main 
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch any Git submodules (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public


YAML workflow:
```

### Relevant log output

[INFO] copy /home/runner/work/anticdimi.github.io/anticdimi.github.io/public to /home/runner/actions_github_pages_1692352328176
  cp: no such file or directory: /home/runner/work/anticdimi.github.io/anticdimi.github.io/public/.*

**Comment by Darker** [comment]
I have the same problem. This is my log:
```
  [INFO] ForceOrphan: false
  /usr/bin/git clone --depth=1 --single-branch --branch gh-pages ***github.com/Darker/battletech-techsheet.git /home/runner/actions_github_pages_1692478804848
  Cloning into '/home/runner/actions_github_pages_1692478804848'...
  [INFO] clean up /home/runner/actions_github_pages_1692478804848
  [INFO] chdir /home/runner/actions_github_pages_1692478804848
  /usr/bin/git rm -r --ignore-unmatch *
  rm '.nojekyll'
  [INFO] chdir /home/runner/actions_github_pages_1692478804848
  [INFO] prepare publishing assets
  [INFO] copy /home/runner/work/battletech-techsheet/battletech-techsheet/web/root to /home/runner/actions_github_pages_1692478804848
  cp: no such file or directory: /home/runner/work/battletech-techsheet/battletech-techsheet/web/root/*
  cp: no such file or directory: /home/runner/work/battletech-techsheet/battletech-techsheet/web/root/.*
  [INFO] delete excluded assets
  rm: no paths given
  [INFO] Created /home/runner/actions_github_pages_1692478804848/.nojekyll
  ```
The only file that ends up in gh-pages branch is the `.nojekyll` file created at the end.

**Comment by peaceiris** [comment]
@anticdimi Your `./public` looks empty, I think.

@Darker Your `./web/root` looks empty too.

**Comment by peaceiris** [comment]
Here is my new example repo. FYI https://github.com/peaceiris/test-mdbook

**Comment by Darker** [comment]
I may have misunderstood the purpose of this action. I thought it would publish from `master` to `gh-pages`. I have in the meantime resolved this by using a different action. Byt my `web/root` in master was not empty: https://github.com/Darker/battletech-techsheet/tree/master/web/root

**Comment by anticdimi** [comment]
Hi @peaceiris ,
I don't think that is the case, because when I run `hugo --minify` on my local machine, the ./public dir actually contains the website content.

**Comment by anticdimi** [comment]
I have also solved this issue by using a different deployment method.
