### ISSUE TITLE
support: Is there a way for me to try a github action to commit a file to gh-page branch from a PR created by a forked repo?

### ISSUE THREAD

**Issue by zhy76** [peaceiris/actions-gh-pages#972]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

I see https://github.com/peaceiris/actions-gh-pages/issues/339#issuecomment-639544093
and I wonder is there a way for me to try a github action to commit a file to gh-page branch from a PR created by a forked repo?

### Relevant links

```markdown
Public repository: https://github.com/kubearmor/kubearmor-action
YAML config: https://github.com/kubearmor/kubearmor-action/actions/runs/5948486423/workflow?pr=18
YAML workflow: https://github.com/kubearmor/kubearmor-action/actions/runs/5948486423/job/16132363497?pr=18
```

**Comment by peaceiris** [comment]
We remain under [the constraints](https://github.com/peaceiris/actions-gh-pages/issues/339#issuecomment-639544093). Even if it's possible, I don't intend to carry it out because it's dangerous.

**Comment by zhy76** [comment]
> We remain under [the constraints](https://github.com/peaceiris/actions-gh-pages/issues/339#issuecomment-639544093). Even if it's possible, I don't intend to carry it out because it's dangerous.

OK, Thanks~
